// GENERATED BY flutter_rust_bridge - DO NOT MODIFY
//
// IO-specific platform bindings for flutter_rust_bridge.
// This file handles native library loading on mobile/desktop.

// ignore_for_file: non_constant_identifier_names, unused_import, prefer_single_quotes

export 'frb_generated.dart';
