// GENERATED BY flutter_rust_bridge - DO NOT MODIFY
//
// This is the main generated entry point for the flutter_rust_bridge
// runtime. It initializes the FFI bridge and provides the
// `RustLib` singleton that the bridge_api.dart methods use.
//
// Regenerate with: flutter_rust_bridge_codegen generate
//
// STUB: This file is a compilable stub. When flutter_rust_bridge_codegen
// runs, it will be replaced with the real generated code.

// ignore_for_file: non_constant_identifier_names, unused_import, unnecessary_import, prefer_single_quotes, always_declare_return_types, require_trailing_commas, depend_on_referenced_packages, library_prefixes, no_leading_underscores_for_local_identifiers, file_names

import 'dart:async';

import 'api/bridge_api.dart';

/// The flutter_rust_bridge runtime singleton.
///
/// Call [RustLib.init] once at app startup to initialize the FFI
/// bridge. After that, all API calls go through
/// `RustLib.instance.api`.
class RustLib {
  RustLib._();

  static RustLib? _instance;

  /// The singleton instance. Throws [StateError] if not initialized.
  static RustLib get instance {
    final inst = _instance;
    if (inst == null) {
      throw StateError(
        'RustLib not initialized. Call RustLib.init() first.',
      );
    }
    return inst;
  }

  /// Whether the bridge has been initialized.
  static bool get isInitialized => _instance != null;

  /// The API wrapper used by [EditorsProEngineApi] to make calls.
  late final EditorsProEngineApi api;

  /// Initialize the bridge. Call this exactly once at app startup.
  ///
  /// When the native library cannot be loaded, a no-op API instance
  /// is created so that the app degrades gracefully.
  static Future<void> init({
    EditorsProEngineApi? apiOverride,
  }) async {
    if (_instance != null) return; // Already initialized

    final inst = RustLib._();

    if (apiOverride != null) {
      inst.api = apiOverride;
    } else {
      // Create a no-op API for graceful degradation when the native
      // engine library is unavailable.
      inst.api = EditorsProEngineApi.noOp();
    }

    _instance = inst;
  }

  /// Dispose of the bridge and release native resources.
  static void dispose() {
    _instance = null;
  }
}
