// GENERATED BY flutter_rust_bridge - DO NOT MODIFY
//
// Web-specific platform bindings for flutter_rust_bridge.
// This file handles WASM module loading for web targets.

// ignore_for_file: non_constant_identifier_names, unused_import, prefer_single_quotes

export 'frb_generated.dart';
