// GENERATED BY flutter_rust_bridge - DO NOT MODIFY
//
// This is the main entry point for the flutter_rust_bridge runtime.
// It initializes the FFI bridge and provides the `RustLib` singleton
// that the bridge_api.dart methods use.
//
// Regenerate with: flutter_rust_bridge_codegen generate
//
// Phase A.1 status: this file has been UPGRADED from a no-op stub to a
// real `dart:ffi`-backed runtime that calls into the C ABI exposed by
// `engine/src/api/ffi_dispatch.rs` (`editors_pro_dispatch`). When the
// team later runs `flutter_rust_bridge_codegen generate`, the generated
// per-method bindings will replace the dispatcher and this file will
// be regenerated by FRB. The dispatcher is intentionally simple so it
// can be removed without a trace once codegen is operational.

// ignore_for_file: non_constant_identifier_names, unused_import, unnecessary_import, prefer_single_quotes, always_declare_return_types, require_trailing_commas, depend_on_referenced_packages, library_prefixes, no_leading_underscores_for_local_identifiers, file_names

import 'dart:async';
import 'dart:ffi' as ffi;
import 'dart:io' show Platform;
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

import 'api/bridge_api.dart';

/// Signature of the native `editors_pro_dispatch` function.
typedef _DispatchNative = ffi.Pointer<ffi.Utf8> Function(
  ffi.Pointer<ffi.Utf8>,
  ffi.Pointer<ffi.Utf8>,
);

/// Dart-side wrapper around the dispatch function.
typedef _DispatchDart = ffi.Pointer<ffi.Utf8> Function(
  ffi.Pointer<ffi.Utf8>,
  ffi.Pointer<ffi.Utf8>,
);

/// Signature of the native `editors_pro_free_string` function.
typedef _FreeStringNative = ffi.Void Function(ffi.Pointer<ffi.Utf8>);
typedef _FreeStringDart = void Function(ffi.Pointer<ffi.Utf8>);

/// The flutter_rust_bridge runtime singleton.
///
/// Call [RustLib.init] once at app startup to initialize the FFI
/// bridge. After that, all API calls go through
/// `RustLib.instance.api`.
class RustLib {
  RustLib._();

  static RustLib? _instance;

  /// The singleton instance. Throws [StateError] if not initialized.
  static RustLib get instance {
    final inst = _instance;
    if (inst == null) {
      throw StateError(
        'RustLib not initialized. Call RustLib.init() first.',
      );
    }
    return inst;
  }

  /// Whether the bridge has been initialized.
  static bool get isInitialized => _instance != null;

  /// The API wrapper used by [EditorsProEngineApi] to make calls.
  late final EditorsProEngineApi api;

  /// The loaded native library, or `null` if loading failed.
  ffi.DynamicLibrary? _dylib;
  _DispatchDart? _dispatch;
  _FreeStringDart? _freeString;

  /// Initialize the bridge. Call this exactly once at app startup.
  ///
  /// When the native library cannot be loaded, a no-op API instance
  /// is created so that the app degrades gracefully.
  static Future<void> init({
    EditorsProEngineApi? apiOverride,
  }) async {
    if (_instance != null) return; // Already initialized

    final inst = RustLib._();

    if (apiOverride != null) {
      inst.api = apiOverride;
    } else {
      // Try to load the native library. On Android the .so is bundled
      // as `libeditors_pro_engine.so`; on Linux dev hosts it may be
      // `libeditors_pro_engine.so` on the LD_LIBRARY_PATH.
      ffi.DynamicLibrary? dylib;
      try {
        dylib = _loadNativeLibrary();
        final dispatchPtr = dylib.lookupFunction<
            _DispatchNative,
            _DispatchDart>('editors_pro_dispatch');
        final freePtr = dylib.lookupFunction<
            _FreeStringNative,
            _FreeStringDart>('editors_pro_free_string');
        inst._dylib = dylib;
        inst._dispatch = dispatchPtr;
        inst._freeString = freePtr;
      } catch (e, st) {
        // Library not found or symbols missing — fall back to noOp.
        print('RustLib: failed to load native engine: $e\n$st');
      }

      if (inst._dispatch != null && inst._freeString != null) {
        inst.api = EditorsProEngineApi(runtime: inst);
      } else {
        // No native engine available — degrade gracefully.
        inst.api = EditorsProEngineApi.noOp();
      }
    }

    _instance = inst;
  }

  /// Dispose of the bridge and release native resources.
  static void dispose() {
    _instance?._dylib?.close();
    _instance = null;
  }

  /// Invoke the native `editors_pro_dispatch` and return the raw JSON
  /// response string. Used by [EditorsProEngineApi._call].
  ///
  /// Throws [StateError] if the native library is not loaded.
  String dispatchRaw(String method, String argsJson) {
    final dispatch = _dispatch;
    final freeString = _freeString;
    if (dispatch == null || freeString == null) {
      throw StateError(
        'Native engine not loaded. Ensure libeditors_pro_engine.so is '
        'bundled in android/app/src/main/jniLibs/<abi>/.',
      );
    }

    // Allocate native UTF-8 strings using `calloc` so we can free them
    // with `calloc.free` (the matching deallocator). The `Utf8` extension
    // method `toNativeUtf8` defaults to `malloc`, so we pass `calloc`
    // explicitly via the allocator parameter.
    final methodPtr = method.toNativeUtf8(allocator: calloc);
    final argsPtr = argsJson.toNativeUtf8(allocator: calloc);
    try {
      final resultPtr = dispatch(methodPtr, argsPtr);
      if (resultPtr == ffi.nullptr) {
        throw StateError('Native dispatch returned null for "$method"');
      }
      try {
        // Copy to Dart string before freeing the native buffer.
        return resultPtr.toDartString();
      } finally {
        freeString(resultPtr);
      }
    } finally {
      calloc.free(methodPtr);
      calloc.free(argsPtr);
    }
  }
}

/// Try to load the native engine library on the current platform.
///
/// On Android we use the bundled `.so` via `DynamicLibrary.open`.
/// On Linux dev hosts we try several common names. On other platforms
/// (iOS, macOS, Windows) we currently return null — to be wired up
/// when the team adds those build targets.
ffi.DynamicLibrary _loadNativeLibrary() {
  if (Platform.isAndroid) {
    return ffi.DynamicLibrary.open('libeditors_pro_engine.so');
  }
  if (Platform.isLinux) {
    // Dev-host fallback (e.g. for `flutter test` on Linux).
    return ffi.DynamicLibrary.open('libeditors_pro_engine.so');
  }
  if (Platform.isMacOS) {
    return ffi.DynamicLibrary.open('libeditors_pro_engine.dylib');
  }
  if (Platform.isWindows) {
    return ffi.DynamicLibrary.open('editors_pro_engine.dll');
  }
  if (Platform.isIOS) {
    // On iOS, statically linked symbols are accessible via the process handle.
    return ffi.DynamicLibrary.process();
  }
  throw UnsupportedError(
    'Native engine library not configured for platform ${Platform.operatingSystem}',
  );
}

/// Suppress unused-import warning for [TypedData] (kept for future use
/// when transferring raw frame bytes via FFI rather than JSON).
// ignore: unused_element
void _useTypedData(TypedData _) {}
