// GENERATED BY flutter_rust_bridge - DO NOT MODIFY
//
// This file contains the Dart-side bridge bindings for the EDITORS-PRO
// Rust engine API. It is automatically generated from the Rust
// `EditorsProEngineApi` struct defined in `engine/src/api/bridge_api.rs`.
//
// Regenerate with: flutter_rust_bridge_codegen generate
//
// STUB: This file is a compilable stub. When flutter_rust_bridge_codegen
// runs, it will be replaced with the real generated code.

// ignore_for_file: non_constant_identifier_names, unused_import, unnecessary_import, unnecessary_brace_in_string_interps, prefer_single_quotes, always_declare_return_types, require_trailing_commas, avoid_positional_boolean_parameters, annotate_overrides, prefer_interpolation_to_compose_strings, unnecessary_string_escapes, directives_ordering, depend_on_referenced_packages, library_prefixes, no_leading_underscores_for_local_identifiers, file_names, use_super_parameters, type_literal_in_constant_pattern, unnecessary_null_checks

import 'dart:async';
import 'dart:typed_data' as typed_data;

import '../frb_generated.dart' show RustLib;

// ═══════════════════════════════════════════════════════════════════════
// DTOs (Data Transfer Objects)
// ═══════════════════════════════════════════════════════════════════════

/// Bridge-compatible project settings
class BridgeProjectSettings {
  final int width;
  final int height;
  final double fps;

  const BridgeProjectSettings({
    required this.width,
    required this.height,
    required this.fps,
  });

  factory BridgeProjectSettings.fromJson(Map<String, dynamic> json) =>
      BridgeProjectSettings(
        width: json['width'] as int,
        height: json['height'] as int,
        fps: (json['fps'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'width': width,
        'height': height,
        'fps': fps,
      };
}

/// Information about a project returned by the engine
class ProjectInfo {
  final String id;
  final String name;
  final int width;
  final int height;
  final double fps;
  final int durationMs;
  final int trackCount;
  final int mediaCount;

  const ProjectInfo({
    required this.id,
    required this.name,
    required this.width,
    required this.height,
    required this.fps,
    this.durationMs = 0,
    this.trackCount = 0,
    this.mediaCount = 0,
  });

  factory ProjectInfo.fromJson(Map<String, dynamic> json) => ProjectInfo(
        id: json['id'] as String,
        name: json['name'] as String,
        width: json['width'] as int,
        height: json['height'] as int,
        fps: (json['fps'] as num).toDouble(),
        durationMs: json['duration_ms'] as int? ?? 0,
        trackCount: json['track_count'] as int? ?? 0,
        mediaCount: json['media_count'] as int? ?? 0,
      );
}

/// Information about a track in the engine
class TrackInfo {
  final String id;
  final String name;
  final String trackType;
  final bool locked;
  final bool visible;
  final double volume;

  const TrackInfo({
    required this.id,
    required this.name,
    required this.trackType,
    this.locked = false,
    this.visible = true,
    this.volume = 1.0,
  });

  factory TrackInfo.fromJson(Map<String, dynamic> json) => TrackInfo(
        id: json['id'] as String,
        name: json['name'] as String,
        trackType: json['track_type'] as String,
        locked: json['locked'] as bool? ?? false,
        visible: json['visible'] as bool? ?? true,
        volume: (json['volume'] as num?)?.toDouble() ?? 1.0,
      );
}

/// Information about a clip in the engine
class ClipInfo {
  final String id;
  final String trackId;
  final String assetId;
  final int startMs;
  final int durationMs;
  final int trimStartMs;
  final int trimEndMs;

  const ClipInfo({
    required this.id,
    required this.trackId,
    required this.assetId,
    required this.startMs,
    required this.durationMs,
    this.trimStartMs = 0,
    this.trimEndMs = 0,
  });

  factory ClipInfo.fromJson(Map<String, dynamic> json) => ClipInfo(
        id: json['id'] as String,
        trackId: json['track_id'] as String,
        assetId: json['asset_id'] as String,
        startMs: json['start_ms'] as int,
        durationMs: json['duration_ms'] as int,
        trimStartMs: json['trim_start_ms'] as int? ?? 0,
        trimEndMs: json['trim_end_ms'] as int? ?? 0,
      );
}

/// Information about an imported media asset
class MediaAssetInfo {
  final String id;
  final String filePath;
  final String fileName;
  final String mediaType;
  final int? durationMs;
  final int? width;
  final int? height;
  final int fileSizeBytes;
  final String? codec;
  final int? bitrate;

  const MediaAssetInfo({
    required this.id,
    required this.filePath,
    required this.fileName,
    required this.mediaType,
    this.durationMs,
    this.width,
    this.height,
    this.fileSizeBytes = 0,
    this.codec,
    this.bitrate,
  });

  factory MediaAssetInfo.fromJson(Map<String, dynamic> json) => MediaAssetInfo(
        id: json['id'] as String,
        filePath: json['file_path'] as String,
        fileName: json['file_name'] as String,
        mediaType: json['media_type'] as String,
        durationMs: json['duration_ms'] as int?,
        width: json['width'] as int?,
        height: json['height'] as int?,
        fileSizeBytes: json['file_size_bytes'] as int? ?? 0,
        codec: json['codec'] as String?,
        bitrate: json['bitrate'] as int?,
      );
}

/// Export settings for the bridge
class BridgeExportSettings {
  final int width;
  final int height;
  final double fps;
  final int bitrateKbps;
  final String codec;
  final String format;
  final int audioBitrateKbps;
  final int audioSampleRate;
  final int audioChannels;
  final bool includeAudio;
  final bool twoPass;

  const BridgeExportSettings({
    required this.width,
    required this.height,
    required this.fps,
    required this.bitrateKbps,
    required this.codec,
    required this.format,
    this.audioBitrateKbps = 128,
    this.audioSampleRate = 44100,
    this.audioChannels = 2,
    this.includeAudio = true,
    this.twoPass = false,
  });

  factory BridgeExportSettings.fromJson(Map<String, dynamic> json) =>
      BridgeExportSettings(
        width: json['width'] as int,
        height: json['height'] as int,
        fps: (json['fps'] as num).toDouble(),
        bitrateKbps: json['bitrate_kbps'] as int,
        codec: json['codec'] as String,
        format: json['format'] as String,
        audioBitrateKbps: json['audio_bitrate_kbps'] as int? ?? 128,
        audioSampleRate: json['audio_sample_rate'] as int? ?? 44100,
        audioChannels: json['audio_channels'] as int? ?? 2,
        includeAudio: json['include_audio'] as bool? ?? true,
        twoPass: json['two_pass'] as bool? ?? false,
      );

  Map<String, dynamic> toJson() => {
        'width': width,
        'height': height,
        'fps': fps,
        'bitrate_kbps': bitrateKbps,
        'codec': codec,
        'format': format,
        'audio_bitrate_kbps': audioBitrateKbps,
        'audio_sample_rate': audioSampleRate,
        'audio_channels': audioChannels,
        'include_audio': includeAudio,
        'two_pass': twoPass,
      };
}

/// Result of an export operation
class BridgeExportResult {
  final bool success;
  final String outputPath;
  final String fileSizeHuman;
  final String? errorMessage;

  const BridgeExportResult({
    required this.success,
    required this.outputPath,
    required this.fileSizeHuman,
    this.errorMessage,
  });

  factory BridgeExportResult.fromJson(Map<String, dynamic> json) =>
      BridgeExportResult(
        success: json['success'] as bool,
        outputPath: json['output_path'] as String,
        fileSizeHuman: json['file_size_human'] as String,
        errorMessage: json['error_message'] as String?,
      );
}

/// Progress reporting for export operations
class BridgeExportProgress {
  final double progress;
  final int currentFrame;
  final int totalFrames;
  final int estimatedSecondsRemaining;
  final String stageName;

  const BridgeExportProgress({
    required this.progress,
    required this.currentFrame,
    required this.totalFrames,
    required this.estimatedSecondsRemaining,
    required this.stageName,
  });
}

/// Timeline state from the engine
class TimelineState {
  final List<TrackInfo> tracks;
  final int durationMs;

  const TimelineState({
    required this.tracks,
    required this.durationMs,
  });

  factory TimelineState.fromJson(Map<String, dynamic> json) => TimelineState(
        tracks: (json['tracks'] as List)
            .map((e) => TrackInfo.fromJson(e as Map<String, dynamic>))
            .toList(),
        durationMs: json['duration_ms'] as int,
      );
}

/// Information about an effect
class EffectInfo {
  final String id;
  final String name;
  final String effectType;
  final bool enabled;
  final List<EffectParameterInfo> parameters;

  const EffectInfo({
    required this.id,
    required this.name,
    required this.effectType,
    this.enabled = true,
    this.parameters = const [],
  });

  factory EffectInfo.fromJson(Map<String, dynamic> json) => EffectInfo(
        id: json['id'] as String,
        name: json['name'] as String,
        effectType: json['effect_type'] as String,
        enabled: json['enabled'] as bool? ?? true,
        parameters: (json['parameters'] as List?)
                ?.map(
                    (e) => EffectParameterInfo.fromJson(e as Map<String, dynamic>))
                .toList() ??
            [],
      );
}

/// Parameter info for an effect
class EffectParameterInfo {
  final String name;
  final String displayName;
  final double value;
  final double minValue;
  final double maxValue;
  final double defaultValue;

  const EffectParameterInfo({
    required this.name,
    required this.displayName,
    required this.value,
    required this.minValue,
    required this.maxValue,
    required this.defaultValue,
  });

  factory EffectParameterInfo.fromJson(Map<String, dynamic> json) =>
      EffectParameterInfo(
        name: json['name'] as String,
        displayName: json['display_name'] as String,
        value: (json['value'] as num).toDouble(),
        minValue: (json['min_value'] as num).toDouble(),
        maxValue: (json['max_value'] as num).toDouble(),
        defaultValue: (json['default_value'] as num).toDouble(),
      );
}

/// Filter type info for the effect catalog
class FilterTypeInfo {
  final String name;
  final String displayName;
  final String category;
  final List<EffectParameterInfo> parameters;

  const FilterTypeInfo({
    required this.name,
    required this.displayName,
    required this.category,
    this.parameters = const [],
  });

  factory FilterTypeInfo.fromJson(Map<String, dynamic> json) => FilterTypeInfo(
        name: json['name'] as String,
        displayName: json['display_name'] as String,
        category: json['category'] as String,
        parameters: (json['parameters'] as List?)
                ?.map(
                    (e) => EffectParameterInfo.fromJson(e as Map<String, dynamic>))
                .toList() ??
            [],
      );
}

/// Filter preset info
class FilterPresetInfo {
  final String id;
  final String name;
  final String description;
  final List<EffectParameterInfo> parameters;

  const FilterPresetInfo({
    required this.id,
    required this.name,
    required this.description,
    this.parameters = const [],
  });

  factory FilterPresetInfo.fromJson(Map<String, dynamic> json) =>
      FilterPresetInfo(
        id: json['id'] as String,
        name: json['name'] as String,
        description: json['description'] as String,
        parameters: (json['parameters'] as List?)
                ?.map(
                    (e) => EffectParameterInfo.fromJson(e as Map<String, dynamic>))
                .toList() ??
            [],
      );
}

/// Transition info
class TransitionInfo {
  final String id;
  final String transitionType;
  final int durationMs;
  final String direction;

  const TransitionInfo({
    required this.id,
    required this.transitionType,
    required this.durationMs,
    required this.direction,
  });

  factory TransitionInfo.fromJson(Map<String, dynamic> json) => TransitionInfo(
        id: json['id'] as String,
        transitionType: json['transition_type'] as String,
        durationMs: json['duration_ms'] as int,
        direction: json['direction'] as String,
      );
}

/// Transition type info for the catalog
class TransitionTypeInfo {
  final String name;
  final String displayName;
  final String category;

  const TransitionTypeInfo({
    required this.name,
    required this.displayName,
    required this.category,
  });

  factory TransitionTypeInfo.fromJson(Map<String, dynamic> json) =>
      TransitionTypeInfo(
        name: json['name'] as String,
        displayName: json['display_name'] as String,
        category: json['category'] as String,
      );
}

/// Ducking configuration for an audio track
class BridgeDuckingConfig {
  final bool enabled;
  final double duckLevel;

  const BridgeDuckingConfig({
    required this.enabled,
    required this.duckLevel,
  });

  factory BridgeDuckingConfig.fromJson(Map<String, dynamic> json) =>
      BridgeDuckingConfig(
        enabled: json['enabled'] as bool,
        duckLevel: (json['duck_level'] as num).toDouble(),
      );
}

/// Font information for text overlays
class FontInfo {
  final String name;
  final String family;
  final String style;
  final bool isBuiltin;

  const FontInfo({
    required this.name,
    required this.family,
    required this.style,
    required this.isBuiltin,
  });

  factory FontInfo.fromJson(Map<String, dynamic> json) => FontInfo(
    name: json['name'] as String,
    family: json['family'] as String,
    style: json['style'] as String,
    isBuiltin: json['is_builtin'] as bool,
  );
}

/// Audio information for a media file
class BridgeAudioInfo {
  final int sampleRate;
  final int channels;
  final int durationMs;
  final String codecName;

  const BridgeAudioInfo({
    required this.sampleRate,
    required this.channels,
    required this.durationMs,
    required this.codecName,
  });

  factory BridgeAudioInfo.fromJson(Map<String, dynamic> json) =>
      BridgeAudioInfo(
        sampleRate: json['sample_rate'] as int,
        channels: json['channels'] as int,
        durationMs: json['duration_ms'] as int,
        codecName: json['codec_name'] as String,
      );
}

// ═══════════════════════════════════════════════════════════════════════
// Phase 7 — Speed & Keyframe DTOs
// ═══════════════════════════════════════════════════════════════════════

/// A single segment of a speed curve
class BridgeSpeedSegment {
  final int startMs;
  final int endMs;
  final double startSpeed;
  final double endSpeed;
  final String easingName;

  const BridgeSpeedSegment({
    required this.startMs,
    required this.endMs,
    required this.startSpeed,
    required this.endSpeed,
    required this.easingName,
  });

  factory BridgeSpeedSegment.fromJson(Map<String, dynamic> json) =>
      BridgeSpeedSegment(
        startMs: json['start_ms'] as int,
        endMs: json['end_ms'] as int,
        startSpeed: (json['start_speed'] as num).toDouble(),
        endSpeed: (json['end_speed'] as num).toDouble(),
        easingName: json['easing_name'] as String,
      );

  Map<String, dynamic> toJson() => {
        'start_ms': startMs,
        'end_ms': endMs,
        'start_speed': startSpeed,
        'end_speed': endSpeed,
        'easing_name': easingName,
      };
}

/// A speed curve composed of multiple segments
class BridgeSpeedCurve {
  final List<BridgeSpeedSegment> segments;

  const BridgeSpeedCurve({required this.segments});

  factory BridgeSpeedCurve.fromJson(Map<String, dynamic> json) =>
      BridgeSpeedCurve(
        segments: (json['segments'] as List)
            .map((e) =>
                BridgeSpeedSegment.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'segments': segments.map((s) => s.toJson()).toList(),
      };

  /// Convenience: create a constant-speed curve
  factory BridgeSpeedCurve.constant(double speed, {int durationMs = 0x7FFFFFFFFFFFFFFF}) =>
      BridgeSpeedCurve(segments: [
        BridgeSpeedSegment(
          startMs: 0,
          endMs: durationMs,
          startSpeed: speed,
          endSpeed: speed,
          easingName: 'linear',
        ),
      ]);
}

/// Speed segment info returned by the engine
class SpeedSegmentInfo {
  final int startMs;
  final int endMs;
  final double startSpeed;
  final double endSpeed;
  final String easingName;

  const SpeedSegmentInfo({
    required this.startMs,
    required this.endMs,
    required this.startSpeed,
    required this.endSpeed,
    required this.easingName,
  });

  factory SpeedSegmentInfo.fromJson(Map<String, dynamic> json) =>
      SpeedSegmentInfo(
        startMs: json['start_ms'] as int,
        endMs: json['end_ms'] as int,
        startSpeed: (json['start_speed'] as num).toDouble(),
        endSpeed: (json['end_speed'] as num).toDouble(),
        easingName: json['easing_name'] as String,
      );
}

/// Speed curve info returned by the engine
class SpeedCurveInfo {
  final List<SpeedSegmentInfo> segments;

  const SpeedCurveInfo({required this.segments});

  factory SpeedCurveInfo.fromJson(Map<String, dynamic> json) => SpeedCurveInfo(
        segments: (json['segments'] as List)
            .map((e) =>
                SpeedSegmentInfo.fromJson(e as Map<String, dynamic>))
            .toList(),
      );
}

/// Keyframe info returned by the engine
class KeyframeInfo {
  final String id;
  final int timeMs;
  final double value;
  final String easingName;

  const KeyframeInfo({
    required this.id,
    required this.timeMs,
    required this.value,
    required this.easingName,
  });

  factory KeyframeInfo.fromJson(Map<String, dynamic> json) => KeyframeInfo(
        id: json['id'] as String,
        timeMs: json['time_ms'] as int,
        value: (json['value'] as num).toDouble(),
        easingName: json['easing_name'] as String,
      );
}

// ═══════════════════════════════════════════════════════════════════════
// System Monitoring DTOs
// ═══════════════════════════════════════════════════════════════════════

/// Memory pressure level
enum MemoryPressureLevel {
  normal,
  warning,
  critical;

  static MemoryPressureLevel fromString(String name) {
    switch (name) {
      case 'warning':
        return MemoryPressureLevel.warning;
      case 'critical':
        return MemoryPressureLevel.critical;
      default:
        return MemoryPressureLevel.normal;
    }
  }
}

/// System resource usage snapshot
class SystemMetrics {
  final int memoryRssBytes;
  final int memoryPeakBytes;
  final int systemAvailableBytes;
  final int systemTotalBytes;
  final MemoryPressureLevel pressureLevel;
  final int cachedFrames;
  final int cachedAudioBuffers;

  const SystemMetrics({
    required this.memoryRssBytes,
    required this.memoryPeakBytes,
    required this.systemAvailableBytes,
    required this.systemTotalBytes,
    required this.pressureLevel,
    required this.cachedFrames,
    required this.cachedAudioBuffers,
  });

  factory SystemMetrics.fromJson(Map<String, dynamic> json) => SystemMetrics(
        memoryRssBytes: json['memory_rss_bytes'] as int,
        memoryPeakBytes: json['memory_peak_bytes'] as int,
        systemAvailableBytes: json['system_available_bytes'] as int,
        systemTotalBytes: json['system_total_bytes'] as int,
        pressureLevel: MemoryPressureLevel.fromString(
            json['pressure_level'] as String? ?? 'normal'),
        cachedFrames: json['cached_frames'] as int,
        cachedAudioBuffers: json['cached_audio_buffers'] as int,
      );

  /// Human-readable RSS
  String get rssFormatted => _formatBytes(memoryRssBytes);

  /// Human-readable peak
  String get peakFormatted => _formatBytes(memoryPeakBytes);

  /// Human-readable available
  String get availableFormatted => _formatBytes(systemAvailableBytes);

  static String _formatBytes(int bytes) {
    if (bytes >= 1073741824) {
      return '${(bytes / 1073741824).toStringAsFixed(1)} GB';
    } else if (bytes >= 1048576) {
      return '${(bytes / 1048576).toStringAsFixed(1)} MB';
    } else if (bytes >= 1024) {
      return '${(bytes / 1024).toStringAsFixed(1)} KB';
    }
    return '$bytes B';
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Engine API
// ═══════════════════════════════════════════════════════════════════════

/// The main API class exposed to Flutter via flutter_rust_bridge v2.
///
/// When the native engine library is unavailable, the noOp constructor
/// creates an instance that throws [UnimplementedError] on every method
/// call, allowing the app to degrade gracefully.
class EditorsProEngineApi {
  /// Whether this API instance is in noOp (degraded) mode.
  final bool _isNoOp;

  /// Create a real engine API instance backed by the FFI runtime.
  EditorsProEngineApi({required dynamic runtime}) : _isNoOp = false;

  /// Create a no-op API instance for graceful degradation when
  /// the native engine library is unavailable.
  EditorsProEngineApi.noOp() : _isNoOp = true;

  /// Check whether this API instance has a working FFI connection.
  bool get isEngineAvailable => !_isNoOp;

  /// Execute a Rust method via the FRB runtime.
  ///
  /// If the engine is not available, throws [UnimplementedError].
  Future<T> _call<T>(String method, Map<String, dynamic> args) async {
    throw UnimplementedError(
      'Bridge method "$method" is not yet wired. '
      'Run `flutter_rust_bridge_codegen generate` to create the '
      'real FFI bindings.',
    );
  }

  // ─── Lifecycle ────────────────────────────────────────────────────

  /// Initialize the engine.
  Future<void> initialize() async {
    return await _call<void>('initialize', {});
  }

  // ─── Project Operations ───────────────────────────────────────────

  /// Create a new project with the given name and optional settings.
  Future<ProjectInfo> createProject({
    required String name,
    BridgeProjectSettings? settings,
  }) async {
    final result = await _call<dynamic>('create_project', {
      'name': name,
      'settings': settings?.toJson(),
    });
    return ProjectInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Import a media file into the current project.
  Future<MediaAssetInfo> importMedia({required String filePath}) async {
    final result =
        await _call<dynamic>('import_media', {'file_path': filePath});
    return MediaAssetInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Save the current project to an .epp file.
  Future<void> saveProject({required String filePath}) async {
    return await _call<void>('save_project', {'path': filePath});
  }

  /// Load a project from an .epp file.
  Future<ProjectInfo> loadProject({required String filePath}) async {
    final result =
        await _call<dynamic>('load_project', {'path': filePath});
    return ProjectInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Get information about the current project.
  Future<ProjectInfo?> getProjectInfo() async {
    final result = await _call<dynamic>('get_project_info', {});
    if (result == null) return null;
    return ProjectInfo.fromJson(result as Map<String, dynamic>);
  }

  // ─── Timeline Operations ─────────────────────────────────────────

  /// Add a track to the timeline.
  Future<TrackInfo> addTrack({
    required String trackType,
    String? name,
  }) async {
    final result = await _call<dynamic>('add_track', {
      'track_type': trackType,
      'name': name,
    });
    return TrackInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Add a clip to a track.
  Future<ClipInfo> addClip({
    required String trackId,
    required String assetId,
    required BigInt startMs,
    required BigInt durationMs,
  }) async {
    final result = await _call<dynamic>('add_clip', {
      'track_id': trackId,
      'asset_id': assetId,
      'start_ms': startMs.toString(),
      'duration_ms': durationMs.toString(),
    });
    return ClipInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Trim a clip by adjusting its in/out points.
  Future<void> trimClip({
    required String clipId,
    required BigInt trimStartMs,
    required BigInt trimEndMs,
  }) async {
    return await _call<void>('trim_clip', {
      'clip_id': clipId,
      'trim_start_ms': trimStartMs.toString(),
      'trim_end_ms': trimEndMs.toString(),
    });
  }

  /// Split a clip at the given timestamp.
  Future<(ClipInfo, ClipInfo)> splitClip({
    required String clipId,
    required BigInt timeMs,
  }) async {
    final result = await _call<dynamic>('split_clip', {
      'clip_id': clipId,
      'time_ms': timeMs.toString(),
    });
    final list = result as List;
    return (
      ClipInfo.fromJson(list[0] as Map<String, dynamic>),
      ClipInfo.fromJson(list[1] as Map<String, dynamic>),
    );
  }

  /// Move a clip to a new position on the timeline.
  Future<void> moveClip({
    required String clipId,
    required BigInt newStartMs,
    String? newTrackId,
  }) async {
    return await _call<void>('move_clip', {
      'clip_id': clipId,
      'new_start_ms': newStartMs.toString(),
      'new_track_id': newTrackId,
    });
  }

  /// Remove a clip from the timeline.
  Future<void> removeClip({required String clipId}) async {
    return await _call<void>('remove_clip', {'clip_id': clipId});
  }

  /// Get the timeline duration in milliseconds.
  Future<BigInt> getTimelineDuration() async {
    final result = await _call<dynamic>('get_timeline_duration', {});
    return BigInt.parse(result.toString());
  }

  /// Get the full timeline state from the engine.
  Future<TimelineState?> getTimelineState() async {
    final result = await _call<dynamic>('get_timeline_state', {});
    if (result == null) return null;
    return TimelineState.fromJson(result as Map<String, dynamic>);
  }

  // ─── Preview ─────────────────────────────────────────────────────

  /// Render a single preview frame at the given timestamp.
  Future<typed_data.Uint8List> getFrame({required BigInt timeMs}) async {
    final result = await _call<dynamic>('get_frame', {
      'time_ms': timeMs.toString(),
    });
    return result as typed_data.Uint8List;
  }

  // ─── Export ──────────────────────────────────────────────────────

  /// Export the project as a video file (synchronous).
  Future<BridgeExportResult> exportVideo({
    required String outputPath,
    required BridgeExportSettings settings,
  }) async {
    final result = await _call<dynamic>('export_video', {
      'output_path': outputPath,
      'settings': settings.toJson(),
    });
    return BridgeExportResult.fromJson(result as Map<String, dynamic>);
  }

  /// Request cancellation of an in-progress export.
  Future<void> cancelExport() async {
    return await _call<void>('cancel_export', {});
  }

  /// Export the project with progress reporting via callback.
  Future<BridgeExportResult> exportVideoWithCallback({
    required String outputPath,
    required BridgeExportSettings settings,
  }) async {
    final result = await _call<dynamic>('export_video_with_callback', {
      'output_path': outputPath,
      'settings': settings.toJson(),
    });
    return BridgeExportResult.fromJson(result as Map<String, dynamic>);
  }

  /// Export the project with streaming progress.
  Stream<BridgeExportProgress> exportVideoStreaming({
    required String outputPath,
    required BridgeExportSettings settings,
  }) {
    final controller = StreamController<BridgeExportProgress>();
    _call<BridgeExportResult>('export_video_streaming', {
      'output_path': outputPath,
      'settings': settings.toJson(),
    }).then((result) {
      controller.add(const BridgeExportProgress(
        progress: 1.0,
        currentFrame: 0,
        totalFrames: 0,
        estimatedSecondsRemaining: 0,
        stageName: 'Complete',
      ));
      controller.close();
    }).catchError((error) {
      controller.addError(error);
      controller.close();
    });
    return controller.stream;
  }

  /// Get the list of available export preset names.
  Future<List<String>> getExportPresets() async {
    final result = await _call<dynamic>('get_export_presets', {});
    return List<String>.from(result as List);
  }

  /// Get the export settings for a named preset.
  Future<BridgeExportSettings?> getExportPreset({required String name}) async {
    final result =
        await _call<dynamic>('get_export_preset', {'name': name});
    if (result == null) return null;
    return BridgeExportSettings.fromJson(result as Map<String, dynamic>);
  }

  // ─── Undo / Redo ─────────────────────────────────────────────────

  /// Undo the last action.
  Future<void> undo() async {
    return await _call<void>('undo', {});
  }

  /// Redo the last undone action.
  Future<void> redo() async {
    return await _call<void>('redo', {});
  }

  /// Check whether undo is available.
  Future<bool> canUndo() async {
    final result = await _call<dynamic>('can_undo', {});
    return result as bool;
  }

  /// Check whether redo is available.
  Future<bool> canRedo() async {
    final result = await _call<dynamic>('can_redo', {});
    return result as bool;
  }

  // ─── Audio Operations ────────────────────────────────────────────

  /// Set the volume level for a track.
  Future<void> setTrackVolume({
    required String trackId,
    required double volume,
  }) async {
    return await _call<void>('set_track_volume', {
      'track_id': trackId,
      'volume': volume,
    });
  }

  /// Toggle track visibility (mute/unmute for audio).
  Future<void> toggleTrackVisibility({required String trackId}) async {
    return await _call<void>(
        'toggle_track_visibility', {'track_id': trackId});
  }

  /// Get audio samples for an asset at a specific time range.
  Future<List<double>> getAudioSamples({
    required String assetId,
    required BigInt startMs,
    required BigInt durationMs,
  }) async {
    final result = await _call<dynamic>('get_audio_samples', {
      'asset_id': assetId,
      'start_ms': startMs.toString(),
      'duration_ms': durationMs.toString(),
    });
    return (result as List).map((e) => (e as num).toDouble()).toList();
  }

  /// Mix all audio tracks at the given timeline position.
  Future<List<double>> mixAudioAtTime({
    required BigInt startMs,
    required BigInt durationMs,
  }) async {
    final result = await _call<dynamic>('mix_audio_at_time', {
      'start_ms': startMs.toString(),
      'duration_ms': durationMs.toString(),
    });
    return (result as List).map((e) => (e as num).toDouble()).toList();
  }

  /// Get waveform peak data for an audio asset.
  Future<List<double>> getWaveform({
    required String assetId,
    required int numBins,
  }) async {
    final result = await _call<dynamic>('get_waveform', {
      'asset_id': assetId,
      'num_bins': numBins,
    });
    return (result as List).map((e) => (e as num).toDouble()).toList();
  }

  /// Configure audio ducking for a track.
  Future<void> setDucking({
    required String trackId,
    required bool enabled,
    required double duckLevel,
  }) async {
    return await _call<void>('set_ducking', {
      'track_id': trackId,
      'enabled': enabled,
      'duck_level': duckLevel,
    });
  }

  /// Get the ducking configuration for a track.
  Future<BridgeDuckingConfig> getDuckingConfig({
    required String trackId,
  }) async {
    final result =
        await _call<dynamic>('get_ducking_config', {'track_id': trackId});
    return BridgeDuckingConfig.fromJson(result as Map<String, dynamic>);
  }

  /// Get audio information for a media file.
  Future<BridgeAudioInfo> getAudioInfo({required String filePath}) async {
    final result =
        await _call<dynamic>('get_audio_info', {'file_path': filePath});
    return BridgeAudioInfo.fromJson(result as Map<String, dynamic>);
  }

  // ─── Effect Operations ───────────────────────────────────────────

  /// Add a filter effect to a clip.
  Future<EffectInfo> addEffect({
    required String clipId,
    required String filterTypeName,
  }) async {
    final result = await _call<dynamic>('add_effect', {
      'clip_id': clipId,
      'filter_type_name': filterTypeName,
    });
    return EffectInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Remove an effect from a clip.
  Future<void> removeEffect({
    required String clipId,
    required String effectId,
  }) async {
    return await _call<void>('remove_effect', {
      'clip_id': clipId,
      'effect_id': effectId,
    });
  }

  /// Set a parameter value for an effect on a clip.
  Future<void> setEffectParameter({
    required String clipId,
    required String effectId,
    required String paramName,
    required double value,
  }) async {
    return await _call<void>('set_effect_parameter', {
      'clip_id': clipId,
      'effect_id': effectId,
      'param_name': paramName,
      'value': value,
    });
  }

  /// Get the effects applied to a clip.
  Future<List<EffectInfo>> getClipEffects({required String clipId}) async {
    final result =
        await _call<dynamic>('get_clip_effects', {'clip_id': clipId});
    return (result as List)
        .map((e) => EffectInfo.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  /// Toggle the enabled/disabled state of an effect on a clip.
  Future<void> toggleEffect({
    required String clipId,
    required String effectId,
  }) async {
    return await _call<void>('toggle_effect', {
      'clip_id': clipId,
      'effect_id': effectId,
    });
  }

  /// Get the catalog of all available filter types.
  Future<List<FilterTypeInfo>> getFilterCatalog() async {
    final result = await _call<dynamic>('get_filter_catalog', {});
    return (result as List)
        .map((e) => FilterTypeInfo.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  /// Get the list of available filter presets.
  Future<List<FilterPresetInfo>> getFilterPresets() async {
    final result = await _call<dynamic>('get_filter_presets', {});
    return (result as List)
        .map((e) => FilterPresetInfo.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  /// Apply a filter preset to a clip (replaces all existing effects).
  Future<void> applyFilterPreset({
    required String clipId,
    required String presetId,
  }) async {
    return await _call<void>('apply_filter_preset', {
      'clip_id': clipId,
      'preset_id': presetId,
    });
  }

  // ─── Transition Operations ───────────────────────────────────────

  /// Add a transition to a clip.
  Future<TransitionInfo> addTransition({
    required String clipId,
    required String transitionType,
    required BigInt durationMs,
    required String direction,
  }) async {
    final result = await _call<dynamic>('add_transition', {
      'clip_id': clipId,
      'transition_type': transitionType,
      'duration_ms': durationMs.toString(),
      'direction': direction,
    });
    return TransitionInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Get the transition on a clip (in-point or out-point).
  Future<TransitionInfo?> getClipTransition({
    required String clipId,
    required String direction,
  }) async {
    final result = await _call<dynamic>('get_clip_transition', {
      'clip_id': clipId,
      'direction': direction,
    });
    if (result == null) return null;
    return TransitionInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Remove a transition from a clip.
  Future<void> removeTransition({
    required String clipId,
    required String direction,
  }) async {
    return await _call<void>('remove_transition', {
      'clip_id': clipId,
      'direction': direction,
    });
  }

  /// Get the catalog of all available transition types.
  Future<List<TransitionTypeInfo>> getTransitionCatalog() async {
    final result = await _call<dynamic>('get_transition_catalog', {});
    return (result as List)
        .map((e) => TransitionTypeInfo.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  // ─── Text Overlay Operations ─────────────────────────────────────

  /// Add a text clip to a track.
  Future<ClipInfo> addTextClip({
    required String trackId,
    required String text,
    required String fontFamily,
    required double fontSize,
    required String colorHex,
    required double positionX,
    required double positionY,
    required int startMs,
    required int durationMs,
  }) async {
    final result = await _call<dynamic>('add_text_clip', {
      'track_id': trackId,
      'text': text,
      'font_family': fontFamily,
      'font_size': fontSize,
      'color_hex': colorHex,
      'position_x': positionX,
      'position_y': positionY,
      'start_ms': startMs.toString(),
      'duration_ms': durationMs.toString(),
    });
    return ClipInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Set the position of a text overlay clip.
  Future<void> setTextPosition({
    required String clipId,
    required double positionX,
    required double positionY,
  }) async {
    return await _call<void>('set_text_position', {
      'clip_id': clipId,
      'position_x': positionX,
      'position_y': positionY,
    });
  }

  /// Set the style of a text overlay clip.
  Future<void> setTextStyle({
    required String clipId,
    required String fontFamily,
    required double fontSize,
    required String colorHex,
  }) async {
    return await _call<void>('set_text_style', {
      'clip_id': clipId,
      'font_family': fontFamily,
      'font_size': fontSize,
      'color_hex': colorHex,
    });
  }

  /// Get the list of available fonts for text overlays.
  Future<List<FontInfo>> getAvailableFonts() async {
    final result = await _call<dynamic>('get_available_fonts', {});
    return (result as List)
        .map((e) => FontInfo.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  // ─── Speed Curve Operations (Phase 7) ──────────────────────────────

  /// Set a multi-segment speed curve for a clip.
  ///
  /// The [curve] contains one or more [BridgeSpeedSegment] entries that
  /// define variable playback speed within the clip. Pass a single segment
  /// with equal start/end speed for constant speed.
  Future<void> setClipSpeedCurve({
    required String clipId,
    required BridgeSpeedCurve curve,
  }) async {
    return await _call<void>('set_clip_speed_curve', {
      'clip_id': clipId,
      'curve': curve.toJson(),
    });
  }

  /// Get the speed curve info for a clip.
  Future<SpeedCurveInfo> getClipSpeedCurve({required String clipId}) async {
    final result = await _call<dynamic>('get_clip_speed_curve', {
      'clip_id': clipId,
    });
    return SpeedCurveInfo.fromJson(result as Map<String, dynamic>);
  }

  // ─── Keyframe Operations (Phase 7) ─────────────────────────────────

  /// Add a keyframe to a clip's property track.
  ///
  /// [property] must be one of: "position_x", "position_y", "scale",
  /// "rotation", "opacity".
  /// [easingName] must be one of: "linear", "ease_in", "ease_out",
  /// "ease_in_out", "cubic_bezier".
  /// Returns the ID of the newly created keyframe.
  Future<String> addKeyframe({
    required String clipId,
    required String property,
    required int timeMs,
    required double value,
    required String easingName,
  }) async {
    final result = await _call<dynamic>('add_keyframe', {
      'clip_id': clipId,
      'property': property,
      'time_ms': timeMs.toString(),
      'value': value,
      'easing_name': easingName,
    });
    return result as String;
  }

  /// Remove a keyframe by ID from a clip's property track.
  Future<void> removeKeyframe({
    required String clipId,
    required String property,
    required String keyframeId,
  }) async {
    return await _call<void>('remove_keyframe', {
      'clip_id': clipId,
      'property': property,
      'keyframe_id': keyframeId,
    });
  }

  /// Update a keyframe's value and/or easing function.
  Future<void> updateKeyframe({
    required String clipId,
    required String property,
    required String keyframeId,
    double? value,
    String? easingName,
  }) async {
    return await _call<void>('update_keyframe', {
      'clip_id': clipId,
      'property': property,
      'keyframe_id': keyframeId,
      'value': value,
      'easing_name': easingName,
    });
  }

  /// Get all keyframes for a clip's property track.
  Future<List<KeyframeInfo>> getKeyframes({
    required String clipId,
    required String property,
  }) async {
    final result = await _call<dynamic>('get_keyframes', {
      'clip_id': clipId,
      'property': property,
    });
    return (result as List)
        .map((e) => KeyframeInfo.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  /// Get the speed curve for a clip.
  Future<SpeedCurveInfo> getClipSpeedCurve({required String clipId}) async {
    final result = await _call<dynamic>('get_clip_speed_curve', {
      'clip_id': clipId,
    });
    return SpeedCurveInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Get current system metrics for memory monitoring.
  ///
  /// Returns RSS, peak memory, available system memory, pressure level,
  /// and cache statistics.
  Future<SystemMetrics> getSystemMetrics() async {
    final result = await _call<dynamic>('get_system_metrics', {});
    return SystemMetrics.fromJson(result as Map<String, dynamic>);
  }

  /// Check if memory pressure is detected.
  ///
  /// Returns true if the engine is under warning or critical memory
  /// pressure, suggesting that caches should be released.
  Future<bool> isMemoryPressure() async {
    final result = await _call<dynamic>('is_memory_pressure', {});
    return result as bool;
  }
}
