// GENERATED BY flutter_rust_bridge - DO NOT MODIFY
//
// This file contains the Dart-side bridge bindings for the EDITORS-PRO
// Rust engine API. It is automatically generated from the Rust
// `EditorsProEngineApi` struct defined in `engine/src/api/bridge_api.rs`.
//
// Regenerate with: flutter_rust_bridge_codegen generate
//
// Phase A.1 status: the previous stub `_call` (which always threw
// `UnimplementedError`) has been replaced with a real FFI dispatcher
// that calls into `engine/src/api/ffi_dispatch.rs::editors_pro_dispatch`.
// When the team later runs `flutter_rust_bridge_codegen generate`, this
// file will be regenerated by FRB with idiomatic per-method bindings.

// ignore_for_file: non_constant_identifier_names, unused_import, unnecessary_import, unnecessary_brace_in_string_interps, prefer_single_quotes, always_declare_return_types, require_trailing_commas, avoid_positional_boolean_parameters, annotate_overrides, prefer_interpolation_to_compose_strings, unnecessary_string_escapes, directives_ordering, depend_on_referenced_packages, library_prefixes, no_leading_underscores_for_local_identifiers, file_names, use_super_parameters, type_literal_in_constant_pattern, unnecessary_null_checks

import 'dart:async';
import 'dart:convert';
import 'dart:typed_data' as typed_data;

import '../frb_generated.dart' show RustLib;

// ═══════════════════════════════════════════════════════════════════════
// DTOs (Data Transfer Objects)
// ═══════════════════════════════════════════════════════════════════════

/// Bridge-compatible project settings
class BridgeProjectSettings {
  final int width;
  final int height;
  final double fps;

  const BridgeProjectSettings({
    required this.width,
    required this.height,
    required this.fps,
  });

  factory BridgeProjectSettings.fromJson(Map<String, dynamic> json) =>
      BridgeProjectSettings(
        width: json['width'] as int,
        height: json['height'] as int,
        fps: (json['fps'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'width': width,
        'height': height,
        'fps': fps,
      };
}

/// Information about a project returned by the engine
class ProjectInfo {
  final String id;
  final String name;
  final int width;
  final int height;
  final double fps;
  final int durationMs;
  final int trackCount;
  final int mediaCount;

  const ProjectInfo({
    required this.id,
    required this.name,
    required this.width,
    required this.height,
    required this.fps,
    this.durationMs = 0,
    this.trackCount = 0,
    this.mediaCount = 0,
  });

  factory ProjectInfo.fromJson(Map<String, dynamic> json) => ProjectInfo(
        id: json['id'] as String,
        name: json['name'] as String,
        width: json['width'] as int,
        height: json['height'] as int,
        fps: (json['fps'] as num).toDouble(),
        durationMs: json['duration_ms'] as int? ?? 0,
        trackCount: json['track_count'] as int? ?? 0,
        mediaCount: json['media_count'] as int? ?? 0,
      );
}

/// Information about a track in the engine
class TrackInfo {
  final String id;
  final String name;
  final String trackType;
  final bool locked;
  final bool visible;
  final double volume;

  const TrackInfo({
    required this.id,
    required this.name,
    required this.trackType,
    this.locked = false,
    this.visible = true,
    this.volume = 1.0,
  });

  factory TrackInfo.fromJson(Map<String, dynamic> json) => TrackInfo(
        id: json['id'] as String,
        name: json['name'] as String,
        trackType: json['track_type'] as String,
        locked: json['locked'] as bool? ?? false,
        visible: json['visible'] as bool? ?? true,
        volume: (json['volume'] as num?)?.toDouble() ?? 1.0,
      );
}

/// Information about a clip in the engine
class ClipInfo {
  final String id;
  final String trackId;
  final String assetId;
  final int startMs;
  final int durationMs;
  final int trimStartMs;
  final int trimEndMs;

  const ClipInfo({
    required this.id,
    required this.trackId,
    required this.assetId,
    required this.startMs,
    required this.durationMs,
    this.trimStartMs = 0,
    this.trimEndMs = 0,
  });

  factory ClipInfo.fromJson(Map<String, dynamic> json) => ClipInfo(
        id: json['id'] as String,
        trackId: json['track_id'] as String,
        assetId: json['asset_id'] as String,
        startMs: json['start_ms'] as int,
        durationMs: json['duration_ms'] as int,
        trimStartMs: json['trim_start_ms'] as int? ?? 0,
        trimEndMs: json['trim_end_ms'] as int? ?? 0,
      );
}

/// Information about an imported media asset
class MediaAssetInfo {
  final String id;
  final String filePath;
  final String fileName;
  final String mediaType;
  final int? durationMs;
  final int? width;
  final int? height;
  final int fileSizeBytes;
  final String? codec;
  final int? bitrate;

  const MediaAssetInfo({
    required this.id,
    required this.filePath,
    required this.fileName,
    required this.mediaType,
    this.durationMs,
    this.width,
    this.height,
    this.fileSizeBytes = 0,
    this.codec,
    this.bitrate,
  });

  factory MediaAssetInfo.fromJson(Map<String, dynamic> json) => MediaAssetInfo(
        id: json['id'] as String,
        filePath: json['file_path'] as String,
        fileName: json['file_name'] as String,
        mediaType: json['media_type'] as String,
        durationMs: json['duration_ms'] as int?,
        width: json['width'] as int?,
        height: json['height'] as int?,
        fileSizeBytes: json['file_size_bytes'] as int? ?? 0,
        codec: json['codec'] as String?,
        bitrate: json['bitrate'] as int?,
      );
}

/// Export settings for the bridge
class BridgeExportSettings {
  final int width;
  final int height;
  final double fps;
  final int bitrateKbps;
  final String codec;
  final String format;
  final int audioBitrateKbps;
  final int audioSampleRate;
  final int audioChannels;
  final bool includeAudio;
  final bool twoPass;

  const BridgeExportSettings({
    required this.width,
    required this.height,
    required this.fps,
    required this.bitrateKbps,
    required this.codec,
    required this.format,
    this.audioBitrateKbps = 128,
    this.audioSampleRate = 44100,
    this.audioChannels = 2,
    this.includeAudio = true,
    this.twoPass = false,
  });

  factory BridgeExportSettings.fromJson(Map<String, dynamic> json) =>
      BridgeExportSettings(
        width: json['width'] as int,
        height: json['height'] as int,
        fps: (json['fps'] as num).toDouble(),
        bitrateKbps: json['bitrate_kbps'] as int,
        codec: json['codec'] as String,
        format: json['format'] as String,
        audioBitrateKbps: json['audio_bitrate_kbps'] as int? ?? 128,
        audioSampleRate: json['audio_sample_rate'] as int? ?? 44100,
        audioChannels: json['audio_channels'] as int? ?? 2,
        includeAudio: json['include_audio'] as bool? ?? true,
        twoPass: json['two_pass'] as bool? ?? false,
      );

  Map<String, dynamic> toJson() => {
        'width': width,
        'height': height,
        'fps': fps,
        'bitrate_kbps': bitrateKbps,
        'codec': codec,
        'format': format,
        'audio_bitrate_kbps': audioBitrateKbps,
        'audio_sample_rate': audioSampleRate,
        'audio_channels': audioChannels,
        'include_audio': includeAudio,
        'two_pass': twoPass,
      };
}

/// Result of an export operation
class BridgeExportResult {
  final bool success;
  final String outputPath;
  final String fileSizeHuman;
  final String? errorMessage;

  const BridgeExportResult({
    required this.success,
    required this.outputPath,
    required this.fileSizeHuman,
    this.errorMessage,
  });

  factory BridgeExportResult.fromJson(Map<String, dynamic> json) =>
      BridgeExportResult(
        success: json['success'] as bool,
        outputPath: json['output_path'] as String,
        fileSizeHuman: json['file_size_human'] as String,
        errorMessage: json['error_message'] as String?,
      );
}

/// Progress reporting for export operations
class BridgeExportProgress {
  final double progress;
  final int currentFrame;
  final int totalFrames;
  final int estimatedSecondsRemaining;
  final String stageName;

  const BridgeExportProgress({
    required this.progress,
    required this.currentFrame,
    required this.totalFrames,
    required this.estimatedSecondsRemaining,
    required this.stageName,
  });
}

/// Phase C.14: A decoded frame streamed from the Rust engine.
///
/// The Rust side pushes these via `StreamSink<BridgeFrame>` when the
/// Dart side calls `streamFrames(startMs, endMs, fps)`. Each frame
/// contains raw RGBA bytes (`width * height * 4` bytes) plus the
/// presentation timestamp.
///
/// To display a `BridgeFrame` in Flutter, convert the RGBA bytes to
/// a `ui.Image` via `dart:ui.Image.fromPixels` (or use the
/// `image` package to encode to PNG first if targeting older Flutter).
class BridgeFrame {
  final int width;
  final int height;
  final typed_data.Uint8List data;
  final int timestampMs;
  final bool isKeyframe;

  const BridgeFrame({
    required this.width,
    required this.height,
    required this.data,
    required this.timestampMs,
    required this.isKeyframe,
  });

  factory BridgeFrame.fromJson(Map<String, dynamic> json) => BridgeFrame(
        width: json['width'] as int,
        height: json['height'] as int,
        data: typed_data.Uint8List.fromList(
          (json['data'] as List).cast<int>(),
        ),
        timestampMs: json['timestamp_ms'] as int,
        isKeyframe: json['is_keyframe'] as bool? ?? false,
      );

  Map<String, dynamic> toJson() => {
        'width': width,
        'height': height,
        'data': data,
        'timestamp_ms': timestampMs,
        'is_keyframe': isKeyframe,
      };
}

/// Timeline state from the engine
class TimelineState {
  final List<TrackInfo> tracks;
  final int durationMs;

  const TimelineState({
    required this.tracks,
    required this.durationMs,
  });

  factory TimelineState.fromJson(Map<String, dynamic> json) => TimelineState(
        tracks: (json['tracks'] as List)
            .map((e) => TrackInfo.fromJson(e as Map<String, dynamic>))
            .toList(),
        durationMs: json['duration_ms'] as int,
      );
}

/// Information about an effect
class EffectInfo {
  final String id;
  final String name;
  final String effectType;
  final bool enabled;
  final List<EffectParameterInfo> parameters;

  const EffectInfo({
    required this.id,
    required this.name,
    required this.effectType,
    this.enabled = true,
    this.parameters = const [],
  });

  factory EffectInfo.fromJson(Map<String, dynamic> json) => EffectInfo(
        id: json['id'] as String,
        name: json['name'] as String,
        effectType: json['effect_type'] as String,
        enabled: json['enabled'] as bool? ?? true,
        parameters: (json['parameters'] as List?)
                ?.map(
                    (e) => EffectParameterInfo.fromJson(e as Map<String, dynamic>))
                .toList() ??
            [],
      );
}

/// Parameter info for an effect
class EffectParameterInfo {
  final String name;
  final String displayName;
  final double value;
  final double minValue;
  final double maxValue;
  final double defaultValue;

  const EffectParameterInfo({
    required this.name,
    required this.displayName,
    required this.value,
    required this.minValue,
    required this.maxValue,
    required this.defaultValue,
  });

  factory EffectParameterInfo.fromJson(Map<String, dynamic> json) =>
      EffectParameterInfo(
        name: json['name'] as String,
        displayName: json['display_name'] as String,
        value: (json['value'] as num).toDouble(),
        minValue: (json['min_value'] as num).toDouble(),
        maxValue: (json['max_value'] as num).toDouble(),
        defaultValue: (json['default_value'] as num).toDouble(),
      );
}

/// Filter type info for the effect catalog
class FilterTypeInfo {
  final String name;
  final String displayName;
  final String category;
  final List<EffectParameterInfo> parameters;

  const FilterTypeInfo({
    required this.name,
    required this.displayName,
    required this.category,
    this.parameters = const [],
  });

  factory FilterTypeInfo.fromJson(Map<String, dynamic> json) => FilterTypeInfo(
        name: json['name'] as String,
        displayName: json['display_name'] as String,
        category: json['category'] as String,
        parameters: (json['parameters'] as List?)
                ?.map(
                    (e) => EffectParameterInfo.fromJson(e as Map<String, dynamic>))
                .toList() ??
            [],
      );
}

/// Filter preset info
class FilterPresetInfo {
  final String id;
  final String name;
  final String description;
  final List<EffectParameterInfo> parameters;

  const FilterPresetInfo({
    required this.id,
    required this.name,
    required this.description,
    this.parameters = const [],
  });

  factory FilterPresetInfo.fromJson(Map<String, dynamic> json) =>
      FilterPresetInfo(
        id: json['id'] as String,
        name: json['name'] as String,
        description: json['description'] as String,
        parameters: (json['parameters'] as List?)
                ?.map(
                    (e) => EffectParameterInfo.fromJson(e as Map<String, dynamic>))
                .toList() ??
            [],
      );
}

/// Transition info
class TransitionInfo {
  final String id;
  final String transitionType;
  final int durationMs;
  final String direction;

  const TransitionInfo({
    required this.id,
    required this.transitionType,
    required this.durationMs,
    required this.direction,
  });

  factory TransitionInfo.fromJson(Map<String, dynamic> json) => TransitionInfo(
        id: json['id'] as String,
        transitionType: json['transition_type'] as String,
        durationMs: json['duration_ms'] as int,
        direction: json['direction'] as String,
      );
}

/// Transition type info for the catalog
class TransitionTypeInfo {
  final String name;
  final String displayName;
  final String category;

  const TransitionTypeInfo({
    required this.name,
    required this.displayName,
    required this.category,
  });

  factory TransitionTypeInfo.fromJson(Map<String, dynamic> json) =>
      TransitionTypeInfo(
        name: json['name'] as String,
        displayName: json['display_name'] as String,
        category: json['category'] as String,
      );
}

/// Ducking configuration for an audio track
class BridgeDuckingConfig {
  final bool enabled;
  final double duckLevel;

  const BridgeDuckingConfig({
    required this.enabled,
    required this.duckLevel,
  });

  factory BridgeDuckingConfig.fromJson(Map<String, dynamic> json) =>
      BridgeDuckingConfig(
        enabled: json['enabled'] as bool,
        duckLevel: (json['duck_level'] as num).toDouble(),
      );
}

/// Font information for text overlays
class FontInfo {
  final String name;
  final String family;
  final String style;
  final bool isBuiltin;

  const FontInfo({
    required this.name,
    required this.family,
    required this.style,
    required this.isBuiltin,
  });

  factory FontInfo.fromJson(Map<String, dynamic> json) => FontInfo(
    name: json['name'] as String,
    family: json['family'] as String,
    style: json['style'] as String,
    isBuiltin: json['is_builtin'] as bool,
  );
}

/// Bridge-compatible transcription segment
///
/// Describes a single transcribed text segment with timing information.
class TranscriptionSegmentInfo {
  final String id;
  final String text;
  final int startMs;
  final int endMs;
  final double confidence;

  const TranscriptionSegmentInfo({
    required this.id,
    required this.text,
    required this.startMs,
    required this.endMs,
    required this.confidence,
  });

  factory TranscriptionSegmentInfo.fromJson(Map<String, dynamic> json) =>
      TranscriptionSegmentInfo(
        id: json['id'] as String,
        text: json['text'] as String,
        startMs: json['start_ms'] as int,
        endMs: json['end_ms'] as int,
        confidence: (json['confidence'] as num).toDouble(),
      );

  /// Duration of this segment in milliseconds
  int get durationMs => endMs - startMs;
}

/// Audio information for a media file
class BridgeAudioInfo {
  final int sampleRate;
  final int channels;
  final int durationMs;
  final String codecName;

  const BridgeAudioInfo({
    required this.sampleRate,
    required this.channels,
    required this.durationMs,
    required this.codecName,
  });

  factory BridgeAudioInfo.fromJson(Map<String, dynamic> json) =>
      BridgeAudioInfo(
        sampleRate: json['sample_rate'] as int,
        channels: json['channels'] as int,
        durationMs: json['duration_ms'] as int,
        codecName: json['codec_name'] as String,
      );
}

// ═══════════════════════════════════════════════════════════════════════
// Phase 7 — Speed & Keyframe DTOs
// ═══════════════════════════════════════════════════════════════════════

/// A single segment of a speed curve
class BridgeSpeedSegment {
  final int startMs;
  final int endMs;
  final double startSpeed;
  final double endSpeed;
  final String easingName;

  const BridgeSpeedSegment({
    required this.startMs,
    required this.endMs,
    required this.startSpeed,
    required this.endSpeed,
    required this.easingName,
  });

  factory BridgeSpeedSegment.fromJson(Map<String, dynamic> json) =>
      BridgeSpeedSegment(
        startMs: json['start_ms'] as int,
        endMs: json['end_ms'] as int,
        startSpeed: (json['start_speed'] as num).toDouble(),
        endSpeed: (json['end_speed'] as num).toDouble(),
        easingName: json['easing_name'] as String,
      );

  Map<String, dynamic> toJson() => {
        'start_ms': startMs,
        'end_ms': endMs,
        'start_speed': startSpeed,
        'end_speed': endSpeed,
        'easing_name': easingName,
      };
}

/// A speed curve composed of multiple segments
class BridgeSpeedCurve {
  final List<BridgeSpeedSegment> segments;

  const BridgeSpeedCurve({required this.segments});

  factory BridgeSpeedCurve.fromJson(Map<String, dynamic> json) =>
      BridgeSpeedCurve(
        segments: (json['segments'] as List)
            .map((e) =>
                BridgeSpeedSegment.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'segments': segments.map((s) => s.toJson()).toList(),
      };

  /// Convenience: create a constant-speed curve
  factory BridgeSpeedCurve.constant(double speed, {int durationMs = 0x7FFFFFFFFFFFFFFF}) =>
      BridgeSpeedCurve(segments: [
        BridgeSpeedSegment(
          startMs: 0,
          endMs: durationMs,
          startSpeed: speed,
          endSpeed: speed,
          easingName: 'linear',
        ),
      ]);
}

/// Speed segment info returned by the engine
class SpeedSegmentInfo {
  final int startMs;
  final int endMs;
  final double startSpeed;
  final double endSpeed;
  final String easingName;

  const SpeedSegmentInfo({
    required this.startMs,
    required this.endMs,
    required this.startSpeed,
    required this.endSpeed,
    required this.easingName,
  });

  factory SpeedSegmentInfo.fromJson(Map<String, dynamic> json) =>
      SpeedSegmentInfo(
        startMs: json['start_ms'] as int,
        endMs: json['end_ms'] as int,
        startSpeed: (json['start_speed'] as num).toDouble(),
        endSpeed: (json['end_speed'] as num).toDouble(),
        easingName: json['easing_name'] as String,
      );
}

/// Speed curve info returned by the engine
class SpeedCurveInfo {
  final List<SpeedSegmentInfo> segments;

  const SpeedCurveInfo({required this.segments});

  factory SpeedCurveInfo.fromJson(Map<String, dynamic> json) => SpeedCurveInfo(
        segments: (json['segments'] as List)
            .map((e) =>
                SpeedSegmentInfo.fromJson(e as Map<String, dynamic>))
            .toList(),
      );
}

/// Keyframe info returned by the engine
class KeyframeInfo {
  final String id;
  final int timeMs;
  final double value;
  final String easingName;

  const KeyframeInfo({
    required this.id,
    required this.timeMs,
    required this.value,
    required this.easingName,
  });

  factory KeyframeInfo.fromJson(Map<String, dynamic> json) => KeyframeInfo(
        id: json['id'] as String,
        timeMs: json['time_ms'] as int,
        value: (json['value'] as num).toDouble(),
        easingName: json['easing_name'] as String,
      );
}

// ═══════════════════════════════════════════════════════════════════════
// Phase 10 — Template DTOs
// ═══════════════════════════════════════════════════════════════════════

/// Bridge-compatible template info
///
/// Describes a pre-built template for quick video creation.
class TemplateInfo {
  /// Unique template identifier
  final String id;
  /// Display name of the template
  final String name;
  /// Description of what the template creates
  final String description;
  /// Category name (e.g., "Social", "Cinematic", "Tutorial")
  final String category;
  /// Preview image path for the template thumbnail
  final String previewPath;
  /// Number of placeholder slots that need user media
  final int placeholderCount;
  /// Total duration in milliseconds
  final int durationMs;
  /// Aspect ratio as a string (e.g., "16:9", "9:16", "1:1")
  final String aspectRatio;
  /// Tags for search/filtering
  final List<String> tags;

  const TemplateInfo({
    required this.id,
    required this.name,
    required this.description,
    required this.category,
    required this.previewPath,
    required this.placeholderCount,
    required this.durationMs,
    required this.aspectRatio,
    required this.tags,
  });

  factory TemplateInfo.fromJson(Map<String, dynamic> json) => TemplateInfo(
        id: json['id'] as String,
        name: json['name'] as String,
        description: json['description'] as String,
        category: json['category'] as String,
        previewPath: json['preview_path'] as String,
        placeholderCount: json['placeholder_count'] as int,
        durationMs: json['duration_ms'] as int,
        aspectRatio: json['aspect_ratio'] as String,
        tags: (json['tags'] as List).map((e) => e as String).toList(),
      );
}

// ═══════════════════════════════════════════════════════════════════════
// Phase 8 — GPU Acceleration DTOs
// ═══════════════════════════════════════════════════════════════════════

class ProxyInfo {
  final String assetId;
  final String originalPath;
  final String? proxyPath;
  final String quality;
  final int originalWidth;
  final int originalHeight;
  final int? proxyWidth;
  final int? proxyHeight;
  final int? fileSizeBytes;

  const ProxyInfo({
    required this.assetId,
    required this.originalPath,
    this.proxyPath,
    required this.quality,
    required this.originalWidth,
    required this.originalHeight,
    this.proxyWidth,
    this.proxyHeight,
    this.fileSizeBytes,
  });

  factory ProxyInfo.fromJson(Map<String, dynamic> json) => ProxyInfo(
        assetId: json['asset_id'] as String,
        originalPath: json['original_path'] as String,
        proxyPath: json['proxy_path'] as String?,
        quality: json['quality'] as String,
        originalWidth: json['original_width'] as int,
        originalHeight: json['original_height'] as int,
        proxyWidth: json['proxy_width'] as int?,
        proxyHeight: json['proxy_height'] as int?,
        fileSizeBytes: json['file_size_bytes'] as int?,
      );
}

class SyncResultInfo {
  final bool success;
  final String message;
  final String? projectId;

  const SyncResultInfo({
    required this.success,
    required this.message,
    this.projectId,
  });

  factory SyncResultInfo.fromJson(Map<String, dynamic> json) => SyncResultInfo(
        success: json['success'] as bool? ?? false,
        message: json['message'] as String? ?? '',
        projectId: json['project_id'] as String?,
      );
}

class SyncStatusInfo {
  final String projectId;
  final String status;
  final String statusDisplayName;
  final bool isActionable;
  final int? lastSyncedAt;
  final String? errorMessage;

  const SyncStatusInfo({
    required this.projectId,
    required this.status,
    required this.statusDisplayName,
    required this.isActionable,
    this.lastSyncedAt,
    this.errorMessage,
  });

  factory SyncStatusInfo.fromJson(Map<String, dynamic> json) => SyncStatusInfo(
        projectId: json['project_id'] as String,
        status: json['status'] as String,
        statusDisplayName: json['status_display_name'] as String? ?? '',
        isActionable: json['is_actionable'] as bool? ?? false,
        lastSyncedAt: json['last_synced_at'] as int?,
        errorMessage: json['error_message'] as String?,
      );
}

class CloudProjectInfo {
  final String projectId;
  final String name;
  final int modifiedAt;
  final int sizeBytes;
  final String cloudFileId;
  final String providerName;

  const CloudProjectInfo({
    required this.projectId,
    required this.name,
    required this.modifiedAt,
    required this.sizeBytes,
    required this.cloudFileId,
    required this.providerName,
  });

  factory CloudProjectInfo.fromJson(Map<String, dynamic> json) =>
      CloudProjectInfo(
        projectId: json['project_id'] as String,
        name: json['name'] as String,
        modifiedAt: json['modified_at'] as int? ?? 0,
        sizeBytes: json['size_bytes'] as int? ?? 0,
        cloudFileId: json['cloud_file_id'] as String? ?? '',
        providerName: json['provider_name'] as String? ?? 'Unknown',
      );
}

/// GPU adapter information for hardware acceleration
class GpuInfo {
  final bool available;
  final String adapterName;
  final String backend;
  final int vramBytes;
  final List<String> supportedEffects;
  final bool isHardwareEncoderAvailable;

  const GpuInfo({
    this.available = false,
    this.adapterName = '',
    this.backend = '',
    this.vramBytes = 0,
    this.supportedEffects = const [],
    this.isHardwareEncoderAvailable = false,
  });

  factory GpuInfo.fromJson(Map<String, dynamic> json) => GpuInfo(
        available: json['available'] as bool? ?? false,
        adapterName: json['adapter_name'] as String? ?? '',
        backend: json['backend'] as String? ?? '',
        vramBytes: json['vram_bytes'] as int? ?? 0,
        supportedEffects: (json['supported_effects'] as List?)
                ?.map((e) => e as String)
                .toList() ??
            [],
        isHardwareEncoderAvailable:
            json['is_hardware_encoder_available'] as bool? ?? false,
      );

  /// Human-readable VRAM size
  String get vramFormatted {
    if (vramBytes >= 1073741824) {
      return '${(vramBytes / 1073741824).toStringAsFixed(1)} GB';
    } else if (vramBytes >= 1048576) {
      return '${(vramBytes / 1048576).toStringAsFixed(1)} MB';
    } else if (vramBytes > 0) {
      return '${(vramBytes / 1024).toStringAsFixed(1)} KB';
    }
    return 'Unknown';
  }
}

// ═══════════════════════════════════════════════════════════════════════
// System Monitoring DTOs
// ═══════════════════════════════════════════════════════════════════════

/// Memory pressure level
enum MemoryPressureLevel {
  normal,
  warning,
  critical;

  static MemoryPressureLevel fromString(String name) {
    switch (name) {
      case 'warning':
        return MemoryPressureLevel.warning;
      case 'critical':
        return MemoryPressureLevel.critical;
      default:
        return MemoryPressureLevel.normal;
    }
  }
}

/// System resource usage snapshot
class SystemMetrics {
  final int memoryRssBytes;
  final int memoryPeakBytes;
  final int systemAvailableBytes;
  final int systemTotalBytes;
  final MemoryPressureLevel pressureLevel;
  final int cachedFrames;
  final int cachedAudioBuffers;

  const SystemMetrics({
    required this.memoryRssBytes,
    required this.memoryPeakBytes,
    required this.systemAvailableBytes,
    required this.systemTotalBytes,
    required this.pressureLevel,
    required this.cachedFrames,
    required this.cachedAudioBuffers,
  });

  factory SystemMetrics.fromJson(Map<String, dynamic> json) => SystemMetrics(
        memoryRssBytes: json['memory_rss_bytes'] as int,
        memoryPeakBytes: json['memory_peak_bytes'] as int,
        systemAvailableBytes: json['system_available_bytes'] as int,
        systemTotalBytes: json['system_total_bytes'] as int,
        pressureLevel: MemoryPressureLevel.fromString(
            json['pressure_level'] as String? ?? 'normal'),
        cachedFrames: json['cached_frames'] as int,
        cachedAudioBuffers: json['cached_audio_buffers'] as int,
      );

  /// Human-readable RSS
  String get rssFormatted => _formatBytes(memoryRssBytes);

  /// Human-readable peak
  String get peakFormatted => _formatBytes(memoryPeakBytes);

  /// Human-readable available
  String get availableFormatted => _formatBytes(systemAvailableBytes);

  static String _formatBytes(int bytes) {
    if (bytes >= 1073741824) {
      return '${(bytes / 1073741824).toStringAsFixed(1)} GB';
    } else if (bytes >= 1048576) {
      return '${(bytes / 1048576).toStringAsFixed(1)} MB';
    } else if (bytes >= 1024) {
      return '${(bytes / 1024).toStringAsFixed(1)} KB';
    }
    return '$bytes B';
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Engine API
// ═══════════════════════════════════════════════════════════════════════

/// The main API class exposed to Flutter via flutter_rust_bridge v2.
///
/// When the native engine library is unavailable, the noOp constructor
/// creates an instance that throws [UnimplementedError] on every method
/// call, allowing the app to degrade gracefully.
class EditorsProEngineApi {
  /// Whether this API instance is in noOp (degraded) mode.
  final bool _isNoOp;

  /// The owning [RustLib] runtime, used to invoke the native dispatch
  /// function. Null when in noOp mode.
  final dynamic _runtime;

  /// Create a real engine API instance backed by the FFI runtime.
  EditorsProEngineApi({required dynamic runtime})
      : _isNoOp = false,
        _runtime = runtime;

  /// Create a no-op API instance for graceful degradation when
  /// the native engine library is unavailable.
  EditorsProEngineApi.noOp()
      : _isNoOp = true,
        _runtime = null;

  /// Check whether this API instance has a working FFI connection.
  bool get isEngineAvailable => !_isNoOp;

  /// Execute a Rust method via the FFI dispatcher.
  ///
  /// Phase A.1: this now actually calls into the native
  /// `editors_pro_dispatch` function exposed by
  /// `engine/src/api/ffi_dispatch.rs`, replacing the previous stub
  /// that threw `UnimplementedError` on every call.
  ///
  /// The dispatcher returns a JSON string of the form
  /// `{"ok": true, "data": ...}` or `{"ok": false, "error": "..."}`.
  /// This method decodes that envelope and either returns the `data`
  /// field cast to `T`, or throws the error message.
  ///
  /// If the engine is not available, throws [UnimplementedError].
  Future<T> _call<T>(String method, Map<String, dynamic> args) async {
    if (_isNoOp || _runtime == null) {
      throw UnimplementedError(
        'Bridge method "$method" cannot run: engine is in noOp mode. '
        'Ensure libeditors_pro_engine.so is bundled and RustLib.init() '
        'successfully loaded the native library.',
      );
    }

    final argsJson = args.isEmpty ? '{}' : _encodeArgs(args);
    final responseJson = _runtime.dispatchRaw(method, argsJson);
    final envelope = _decodeEnvelope(responseJson);

    if (!envelope['ok']) {
      final err = envelope['error'] ?? 'unknown error';
      throw Exception('Engine $method failed: $err');
    }
    final data = envelope['data'];
    return data as T;
  }

  /// Encode Dart args to a JSON string. Uses [jsonEncode] which handles
  /// nested maps and lists but not BigInt — callers must convert BigInt
  /// values to strings before passing them in (which they already do).
  static String _encodeArgs(Map<String, dynamic> args) {
    return args.isEmpty
        ? '{}'
        : jsonEncode(args, toEncodable: (obj) {
            if (obj is BigInt) return obj.toString();
            // Try to call toJson() on the object if it has one.
            // This handles DTOs like BridgeProjectSettings, BridgeExportSettings, etc.
            // that were passed as objects rather than pre-converted Maps.
            // Using a dynamic dispatch with try/catch because `obj?.toJson`
            // would try to access `toJson` as a getter (tear-off) rather
            // than checking if it's a method.
            try {
              final json = (obj as dynamic).toJson();
              if (json is Map) return json;
            } catch (_) {
              // No toJson method — fall through to toString()
            }
            return obj.toString();
          });
  }

  /// Decode a JSON envelope returned by the dispatcher.
  static Map<String, dynamic> _decodeEnvelope(String json) {
    final decoded = jsonDecode(json);
    if (decoded is! Map) {
      throw FormatException(
        'Expected JSON object from dispatcher, got: ${decoded.runtimeType}',
      );
    }
    return decoded.cast<String, dynamic>();
  }

  // ─── Lifecycle ────────────────────────────────────────────────────

  /// Initialize the engine.
  Future<void> initialize() async {
    return await _call<void>('initialize', {});
  }

  // ─── Project Operations ───────────────────────────────────────────

  /// Create a new project with the given name and optional settings.
  Future<ProjectInfo> createProject({
    required String name,
    BridgeProjectSettings? settings,
  }) async {
    final result = await _call<dynamic>('create_project', {
      'name': name,
      'settings': settings?.toJson(),
    });
    return ProjectInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Import a media file into the current project.
  Future<MediaAssetInfo> importMedia({required String filePath}) async {
    final result =
        await _call<dynamic>('import_media', {'file_path': filePath});
    return MediaAssetInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Save the current project to an .epp file.
  Future<void> saveProject({required String filePath}) async {
    return await _call<void>('save_project', {'path': filePath});
  }

  /// Load a project from an .epp file.
  Future<ProjectInfo> loadProject({required String filePath}) async {
    final result =
        await _call<dynamic>('load_project', {'path': filePath});
    return ProjectInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Get information about the current project.
  Future<ProjectInfo?> getProjectInfo() async {
    final result = await _call<dynamic>('get_project_info', {});
    if (result == null) return null;
    return ProjectInfo.fromJson(result as Map<String, dynamic>);
  }

  // ─── Timeline Operations ─────────────────────────────────────────

  /// Add a track to the timeline.
  Future<TrackInfo> addTrack({
    required String trackType,
    String? name,
  }) async {
    final result = await _call<dynamic>('add_track', {
      'track_type': trackType,
      'name': name,
    });
    return TrackInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Add a clip to a track.
  Future<ClipInfo> addClip({
    required String trackId,
    required String assetId,
    required BigInt startMs,
    required BigInt durationMs,
  }) async {
    final result = await _call<dynamic>('add_clip', {
      'track_id': trackId,
      'asset_id': assetId,
      'start_ms': startMs.toString(),
      'duration_ms': durationMs.toString(),
    });
    return ClipInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Trim a clip by adjusting its in/out points.
  Future<void> trimClip({
    required String clipId,
    required BigInt trimStartMs,
    required BigInt trimEndMs,
  }) async {
    return await _call<void>('trim_clip', {
      'clip_id': clipId,
      'trim_start_ms': trimStartMs.toString(),
      'trim_end_ms': trimEndMs.toString(),
    });
  }

  /// Split a clip at the given timestamp.
  Future<(ClipInfo, ClipInfo)> splitClip({
    required String clipId,
    required BigInt timeMs,
  }) async {
    final result = await _call<dynamic>('split_clip', {
      'clip_id': clipId,
      'time_ms': timeMs.toString(),
    });
    final list = result as List;
    return (
      ClipInfo.fromJson(list[0] as Map<String, dynamic>),
      ClipInfo.fromJson(list[1] as Map<String, dynamic>),
    );
  }

  /// Move a clip to a new position on the timeline.
  Future<void> moveClip({
    required String clipId,
    required BigInt newStartMs,
    String? newTrackId,
  }) async {
    return await _call<void>('move_clip', {
      'clip_id': clipId,
      'new_start_ms': newStartMs.toString(),
      'new_track_id': newTrackId,
    });
  }

  /// Remove a clip from the timeline.
  Future<void> removeClip({required String clipId}) async {
    return await _call<void>('remove_clip', {'clip_id': clipId});
  }

  /// Get the timeline duration in milliseconds.
  Future<BigInt> getTimelineDuration() async {
    final result = await _call<dynamic>('get_timeline_duration', {});
    return BigInt.parse(result.toString());
  }

  /// Get the full timeline state from the engine.
  Future<TimelineState?> getTimelineState() async {
    final result = await _call<dynamic>('get_timeline_state', {});
    if (result == null) return null;
    return TimelineState.fromJson(result as Map<String, dynamic>);
  }

  // ─── Preview ─────────────────────────────────────────────────────

  /// Render a single preview frame at the given timestamp.
  Future<typed_data.Uint8List> getFrame({required BigInt timeMs}) async {
    final result = await _call<dynamic>('get_frame', {
      'time_ms': timeMs.toString(),
    });
    // The dispatcher returns a JSON array of ints (from Rust Vec<u8>).
    // jsonDecode produces a List<dynamic>, which we convert to Uint8List.
    if (result is typed_data.Uint8List) return result;
    if (result is List) {
      return typed_data.Uint8List.fromList(result.cast<int>());
    }
    throw FormatException(
      'Expected Uint8List or List from get_frame, got ${result.runtimeType}',
    );
  }

  /// Phase C.14: stream frames from `startMs` to `endMs` at the given `fps`.
  ///
  /// Returns a `Stream<BridgeFrame>` that the caller can listen on.
  /// Each frame is pushed by the Rust side as soon as it's decoded,
  /// eliminating FFI round-trip latency for preview playback.
  ///
  /// **Note**: this method requires real flutter_rust_bridge bindings
  /// (i.e., `flutter_rust_bridge_codegen generate` has been run). With
  /// the FFI dispatcher fallback, this method throws `UnimplementedError`
  /// — use `getFrame` polling as a fallback.
  ///
  /// To cancel the stream, cancel the `StreamSubscription` returned by
  /// `listen()`. The Rust side detects the closed sink and exits.
  Stream<BridgeFrame> streamFrames({
    required BigInt startMs,
    required BigInt endMs,
    required double fps,
  }) {
    // The dispatcher can't pass a StreamSink across plain C FFI, so
    // this method only works with real flutter_rust_bridge bindings.
    // When codegen is run, this method will be replaced with a real
    // implementation that creates a StreamSink and passes it to
    // `RustLib.instance.api.stream_frames(start_ms, end_ms, fps, sink)`.
    //
    // For now, throw UnimplementedError so callers know to fall back
    // to `getFrame` polling.
    throw UnimplementedError(
      'streamFrames requires flutter_rust_bridge_codegen to be run. '
      'Until then, use getFrame() polling as a fallback.',
    );
  }

  // ─── Export ──────────────────────────────────────────────────────

  /// Export the project as a video file (synchronous).
  Future<BridgeExportResult> exportVideo({
    required String outputPath,
    required BridgeExportSettings settings,
  }) async {
    final result = await _call<dynamic>('export_video', {
      'output_path': outputPath,
      'settings': settings.toJson(),
    });
    return BridgeExportResult.fromJson(result as Map<String, dynamic>);
  }

  /// Request cancellation of an in-progress export.
  Future<void> cancelExport() async {
    return await _call<void>('cancel_export', {});
  }

  /// Export the project with progress reporting via callback.
  Future<BridgeExportResult> exportVideoWithCallback({
    required String outputPath,
    required BridgeExportSettings settings,
  }) async {
    final result = await _call<dynamic>('export_video_with_callback', {
      'output_path': outputPath,
      'settings': settings.toJson(),
    });
    return BridgeExportResult.fromJson(result as Map<String, dynamic>);
  }

  /// Export the project with streaming progress.
  Stream<BridgeExportProgress> exportVideoStreaming({
    required String outputPath,
    required BridgeExportSettings settings,
  }) {
    final controller = StreamController<BridgeExportProgress>();
    _call<BridgeExportResult>('export_video_streaming', {
      'output_path': outputPath,
      'settings': settings.toJson(),
    }).then((result) {
      controller.add(const BridgeExportProgress(
        progress: 1.0,
        currentFrame: 0,
        totalFrames: 0,
        estimatedSecondsRemaining: 0,
        stageName: 'Complete',
      ));
      controller.close();
    }).catchError((error) {
      controller.addError(error);
      controller.close();
    });
    return controller.stream;
  }

  /// Get the list of available export preset names.
  Future<List<String>> getExportPresets() async {
    final result = await _call<dynamic>('get_export_presets', {});
    return List<String>.from(result as List);
  }

  /// Get the export settings for a named preset.
  Future<BridgeExportSettings?> getExportPreset({required String name}) async {
    final result =
        await _call<dynamic>('get_export_preset', {'name': name});
    if (result == null) return null;
    return BridgeExportSettings.fromJson(result as Map<String, dynamic>);
  }

  // ─── Undo / Redo ─────────────────────────────────────────────────

  /// Undo the last action.
  Future<void> undo() async {
    return await _call<void>('undo', {});
  }

  /// Redo the last undone action.
  Future<void> redo() async {
    return await _call<void>('redo', {});
  }

  /// Check whether undo is available.
  Future<bool> canUndo() async {
    final result = await _call<dynamic>('can_undo', {});
    return result as bool;
  }

  /// Check whether redo is available.
  Future<bool> canRedo() async {
    final result = await _call<dynamic>('can_redo', {});
    return result as bool;
  }

  // ─── Audio Operations ────────────────────────────────────────────

  /// Set the volume level for a track.
  Future<void> setTrackVolume({
    required String trackId,
    required double volume,
  }) async {
    return await _call<void>('set_track_volume', {
      'track_id': trackId,
      'volume': volume,
    });
  }

  /// Toggle track visibility (mute/unmute for audio).
  Future<void> toggleTrackVisibility({required String trackId}) async {
    return await _call<void>(
        'toggle_track_visibility', {'track_id': trackId});
  }

  /// Get audio samples for an asset at a specific time range.
  Future<List<double>> getAudioSamples({
    required String assetId,
    required BigInt startMs,
    required BigInt durationMs,
  }) async {
    final result = await _call<dynamic>('get_audio_samples', {
      'asset_id': assetId,
      'start_ms': startMs.toString(),
      'duration_ms': durationMs.toString(),
    });
    return (result as List).map((e) => (e as num).toDouble()).toList();
  }

  /// Mix all audio tracks at the given timeline position.
  Future<List<double>> mixAudioAtTime({
    required BigInt startMs,
    required BigInt durationMs,
  }) async {
    final result = await _call<dynamic>('mix_audio_at_time', {
      'start_ms': startMs.toString(),
      'duration_ms': durationMs.toString(),
    });
    return (result as List).map((e) => (e as num).toDouble()).toList();
  }

  /// Get waveform peak data for an audio asset.
  Future<List<double>> getWaveform({
    required String assetId,
    required int numBins,
  }) async {
    final result = await _call<dynamic>('get_waveform', {
      'asset_id': assetId,
      'num_bins': numBins,
    });
    return (result as List).map((e) => (e as num).toDouble()).toList();
  }

  /// Configure audio ducking for a track.
  Future<void> setDucking({
    required String trackId,
    required bool enabled,
    required double duckLevel,
  }) async {
    return await _call<void>('set_ducking', {
      'track_id': trackId,
      'enabled': enabled,
      'duck_level': duckLevel,
    });
  }

  /// Get the ducking configuration for a track.
  Future<BridgeDuckingConfig> getDuckingConfig({
    required String trackId,
  }) async {
    final result =
        await _call<dynamic>('get_ducking_config', {'track_id': trackId});
    return BridgeDuckingConfig.fromJson(result as Map<String, dynamic>);
  }

  /// Get audio information for a media file.
  Future<BridgeAudioInfo> getAudioInfo({required String filePath}) async {
    final result =
        await _call<dynamic>('get_audio_info', {'file_path': filePath});
    return BridgeAudioInfo.fromJson(result as Map<String, dynamic>);
  }

  // ─── Effect Operations ───────────────────────────────────────────

  /// Add a filter effect to a clip.
  Future<EffectInfo> addEffect({
    required String clipId,
    required String filterTypeName,
  }) async {
    final result = await _call<dynamic>('add_effect', {
      'clip_id': clipId,
      'filter_type_name': filterTypeName,
    });
    return EffectInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Remove an effect from a clip.
  Future<void> removeEffect({
    required String clipId,
    required String effectId,
  }) async {
    return await _call<void>('remove_effect', {
      'clip_id': clipId,
      'effect_id': effectId,
    });
  }

  /// Set a parameter value for an effect on a clip.
  Future<void> setEffectParameter({
    required String clipId,
    required String effectId,
    required String paramName,
    required double value,
  }) async {
    return await _call<void>('set_effect_parameter', {
      'clip_id': clipId,
      'effect_id': effectId,
      'param_name': paramName,
      'value': value,
    });
  }

  /// Get the effects applied to a clip.
  Future<List<EffectInfo>> getClipEffects({required String clipId}) async {
    final result =
        await _call<dynamic>('get_clip_effects', {'clip_id': clipId});
    return (result as List)
        .map((e) => EffectInfo.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  /// Toggle the enabled/disabled state of an effect on a clip.
  Future<void> toggleEffect({
    required String clipId,
    required String effectId,
  }) async {
    return await _call<void>('toggle_effect', {
      'clip_id': clipId,
      'effect_id': effectId,
    });
  }

  /// Get the catalog of all available filter types.
  Future<List<FilterTypeInfo>> getFilterCatalog() async {
    final result = await _call<dynamic>('get_filter_catalog', {});
    return (result as List)
        .map((e) => FilterTypeInfo.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  /// Get the list of available filter presets.
  Future<List<FilterPresetInfo>> getFilterPresets() async {
    final result = await _call<dynamic>('get_filter_presets', {});
    return (result as List)
        .map((e) => FilterPresetInfo.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  /// Apply a filter preset to a clip (replaces all existing effects).
  Future<void> applyFilterPreset({
    required String clipId,
    required String presetId,
  }) async {
    return await _call<void>('apply_filter_preset', {
      'clip_id': clipId,
      'preset_id': presetId,
    });
  }

  // ─── Transition Operations ───────────────────────────────────────

  /// Add a transition to a clip.
  Future<TransitionInfo> addTransition({
    required String clipId,
    required String transitionType,
    required BigInt durationMs,
    required String direction,
  }) async {
    final result = await _call<dynamic>('add_transition', {
      'clip_id': clipId,
      'transition_type': transitionType,
      'duration_ms': durationMs.toString(),
      'direction': direction,
    });
    return TransitionInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Get the transition on a clip (in-point or out-point).
  Future<TransitionInfo?> getClipTransition({
    required String clipId,
    required String direction,
  }) async {
    final result = await _call<dynamic>('get_clip_transition', {
      'clip_id': clipId,
      'direction': direction,
    });
    if (result == null) return null;
    return TransitionInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Remove a transition from a clip.
  Future<void> removeTransition({
    required String clipId,
    required String direction,
  }) async {
    return await _call<void>('remove_transition', {
      'clip_id': clipId,
      'direction': direction,
    });
  }

  /// Get the catalog of all available transition types.
  Future<List<TransitionTypeInfo>> getTransitionCatalog() async {
    final result = await _call<dynamic>('get_transition_catalog', {});
    return (result as List)
        .map((e) => TransitionTypeInfo.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  // ─── Text Overlay Operations ─────────────────────────────────────

  /// Add a text clip to a track.
  Future<ClipInfo> addTextClip({
    required String trackId,
    required String text,
    required String fontFamily,
    required double fontSize,
    required String colorHex,
    required double positionX,
    required double positionY,
    required int startMs,
    required int durationMs,
  }) async {
    final result = await _call<dynamic>('add_text_clip', {
      'track_id': trackId,
      'text': text,
      'font_family': fontFamily,
      'font_size': fontSize,
      'color_hex': colorHex,
      'position_x': positionX,
      'position_y': positionY,
      'start_ms': startMs.toString(),
      'duration_ms': durationMs.toString(),
    });
    return ClipInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Set the position of a text overlay clip.
  Future<void> setTextPosition({
    required String clipId,
    required double positionX,
    required double positionY,
  }) async {
    return await _call<void>('set_text_position', {
      'clip_id': clipId,
      'position_x': positionX,
      'position_y': positionY,
    });
  }

  /// Set the style of a text overlay clip.
  Future<void> setTextStyle({
    required String clipId,
    required String fontFamily,
    required double fontSize,
    required String colorHex,
  }) async {
    return await _call<void>('set_text_style', {
      'clip_id': clipId,
      'font_family': fontFamily,
      'font_size': fontSize,
      'color_hex': colorHex,
    });
  }

  /// Get the list of available fonts for text overlays.
  Future<List<FontInfo>> getAvailableFonts() async {
    final result = await _call<dynamic>('get_available_fonts', {});
    return (result as List)
        .map((e) => FontInfo.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  // ─── Speed Curve Operations (Phase 7) ──────────────────────────────

  /// Set a multi-segment speed curve for a clip.
  ///
  /// The [curve] contains one or more [BridgeSpeedSegment] entries that
  /// define variable playback speed within the clip. Pass a single segment
  /// with equal start/end speed for constant speed.
  Future<void> setClipSpeedCurve({
    required String clipId,
    required BridgeSpeedCurve curve,
  }) async {
    return await _call<void>('set_clip_speed_curve', {
      'clip_id': clipId,
      'curve': curve.toJson(),
    });
  }

  /// Get the speed curve info for a clip.
  Future<SpeedCurveInfo> getClipSpeedCurve({required String clipId}) async {
    final result = await _call<dynamic>('get_clip_speed_curve', {
      'clip_id': clipId,
    });
    return SpeedCurveInfo.fromJson(result as Map<String, dynamic>);
  }

  // ─── Keyframe Operations (Phase 7) ─────────────────────────────────

  /// Add a keyframe to a clip's property track.
  ///
  /// [property] must be one of: "position_x", "position_y", "scale",
  /// "rotation", "opacity".
  /// [easingName] must be one of: "linear", "ease_in", "ease_out",
  /// "ease_in_out", "cubic_bezier".
  /// Returns the ID of the newly created keyframe.
  Future<String> addKeyframe({
    required String clipId,
    required String property,
    required int timeMs,
    required double value,
    required String easingName,
  }) async {
    final result = await _call<dynamic>('add_keyframe', {
      'clip_id': clipId,
      'property': property,
      'time_ms': timeMs.toString(),
      'value': value,
      'easing_name': easingName,
    });
    return result as String;
  }

  /// Remove a keyframe by ID from a clip's property track.
  Future<void> removeKeyframe({
    required String clipId,
    required String property,
    required String keyframeId,
  }) async {
    return await _call<void>('remove_keyframe', {
      'clip_id': clipId,
      'property': property,
      'keyframe_id': keyframeId,
    });
  }

  /// Update a keyframe's value and/or easing function.
  Future<void> updateKeyframe({
    required String clipId,
    required String property,
    required String keyframeId,
    double? value,
    String? easingName,
  }) async {
    return await _call<void>('update_keyframe', {
      'clip_id': clipId,
      'property': property,
      'keyframe_id': keyframeId,
      'value': value,
      'easing_name': easingName,
    });
  }

  /// Get all keyframes for a clip's property track.
  Future<List<KeyframeInfo>> getKeyframes({
    required String clipId,
    required String property,
  }) async {
    final result = await _call<dynamic>('get_keyframes', {
      'clip_id': clipId,
      'property': property,
    });
    return (result as List)
        .map((e) => KeyframeInfo.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  /// Get current system metrics for memory monitoring.
  ///
  /// Returns RSS, peak memory, available system memory, pressure level,
  /// and cache statistics.
  Future<SystemMetrics> getSystemMetrics() async {
    final result = await _call<dynamic>('get_system_metrics', {});
    return SystemMetrics.fromJson(result as Map<String, dynamic>);
  }

  /// Check if memory pressure is detected.
  ///
  /// Returns true if the engine is under warning or critical memory
  /// pressure, suggesting that caches should be released.
  Future<bool> isMemoryPressure() async {
    final result = await _call<dynamic>('is_memory_pressure', {});
    return result as bool;
  }

  // ─── GPU Acceleration Operations (Phase 8) ────────────────────────

  /// Check if GPU rendering is available.
  ///
  /// Returns true when a compatible GPU adapter was found during
  /// engine initialization.
  Future<bool> isGpuAvailable() async {
    final result = await _call<dynamic>('is_gpu_available', {});
    return result as bool;
  }

  /// Get GPU adapter information.
  ///
  /// Returns a [GpuInfo] object describing the available GPU adapter,
  /// including its name, backend type, VRAM, and which effects support
  /// GPU acceleration.
  Future<GpuInfo> getGpuInfo() async {
    final result = await _call<dynamic>('get_gpu_info', {});
    return GpuInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Export the project using a hardware encoder when available.
  ///
  /// When a hardware encoder is available (NVENC, VideoToolbox, etc.),
  /// this method uses it for significantly faster encoding. Falls back
  /// to the software encoder if the hardware encoder fails.
  Future<BridgeExportResult> exportVideoHardware({
    required String outputPath,
    required BridgeExportSettings settings,
  }) async {
    final result = await _call<dynamic>('export_video_hardware', {
      'output_path': outputPath,
      'settings': settings.toJson(),
    });
    return BridgeExportResult.fromJson(result as Map<String, dynamic>);
  }

  /// Toggle GPU acceleration on or off.
  ///
  /// When [enabled] is false, the engine will use CPU-only rendering
  /// even if a GPU is available. This is useful for debugging.
  Future<void> setGpuAcceleration({required bool enabled}) async {
    return await _call<void>('set_gpu_acceleration', {'enabled': enabled});
  }

  // ─── Template Operations (Phase 10) ──────────────────────────────

  Future<SyncResultInfo> syncProject({required String projectId}) async {
    final result = await _call<dynamic>('sync_project', {
      'project_id': projectId,
    });
    return SyncResultInfo.fromJson(result as Map<String, dynamic>);
  }

  Future<SyncStatusInfo> getSyncStatus({required String projectId}) async {
    final result = await _call<dynamic>('get_sync_status', {
      'project_id': projectId,
    });
    return SyncStatusInfo.fromJson(result as Map<String, dynamic>);
  }

  Future<List<CloudProjectInfo>> getCloudProjects() async {
    final result = await _call<dynamic>('get_cloud_projects', {});
    return (result as List)
        .map((e) => CloudProjectInfo.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  Future<void> resolveSyncConflict({
    required String projectId,
    required String strategy,
  }) async {
    return await _call<void>('resolve_sync_conflict', {
      'project_id': projectId,
      'strategy': strategy,
    });
  }

  Future<EffectInfo> addChromaKeyEffect({
    required String clipId,
    required double targetHue,
    required double hueTolerance,
    required double saturationTolerance,
    required double softness,
    required double spillSuppression,
  }) async {
    final result = await _call<dynamic>('add_chroma_key_effect', {
      'clip_id': clipId,
      'target_hue': targetHue,
      'hue_tolerance': hueTolerance,
      'saturation_tolerance': saturationTolerance,
      'softness': softness,
      'spill_suppression': spillSuppression,
    });
    return EffectInfo.fromJson(result as Map<String, dynamic>);
  }

  Future<List<double>> pickColorFromFrame({
    required int timeMs,
    required int x,
    required int y,
  }) async {
    final result = await _call<dynamic>('pick_color_from_frame', {
      'time_ms': timeMs,
      'x': x,
      'y': y,
    });
    return (result as List).map((e) => (e as num).toDouble()).toList();
  }

  Future<void> setProxyQuality({required String quality}) async {
    return await _call<void>('set_proxy_quality', {'quality': quality});
  }

  Future<String> getProxyQuality() async {
    final result = await _call<dynamic>('get_proxy_quality', {});
    return result as String;
  }

  Future<String> generateProxy({
    required String assetId,
    required String sourcePath,
  }) async {
    final result = await _call<dynamic>('generate_proxy', {
      'asset_id': assetId,
      'source_path': sourcePath,
    });
    return result as String;
  }

  Future<String?> getProxyPath({required String assetId}) async {
    final result = await _call<dynamic>('get_proxy_path', {
      'asset_id': assetId,
    });
    return result as String?;
  }

  Future<int> clearProxyCache() async {
    final result = await _call<dynamic>('clear_proxy_cache', {});
    return result as int;
  }

  Future<int> getProxyCacheSize() async {
    final result = await _call<dynamic>('get_proxy_cache_size', {});
    return result as int;
  }

  Future<int> getProxyCount() async {
    final result = await _call<dynamic>('get_proxy_count', {});
    return result as int;
  }

  Future<void> setAutoProxy({required bool enabled}) async {
    return await _call<void>('set_auto_proxy', {'enabled': enabled});
  }

  Future<bool> isAutoProxyEnabled() async {
    final result = await _call<dynamic>('is_auto_proxy_enabled', {});
    return result as bool;
  }

  Future<String> regenerateProxy({required String assetId}) async {
    final result = await _call<dynamic>('regenerate_proxy', {
      'asset_id': assetId,
    });
    return result as String;
  }

  Future<bool> shouldGenerateProxy({
    required int width,
    required int height,
  }) async {
    final result = await _call<dynamic>('should_generate_proxy', {
      'width': width,
      'height': height,
    });
    return result as bool;
  }

  Future<ProxyInfo?> getProxyInfo({required String assetId}) async {
    final result = await _call<dynamic>('get_proxy_info', {
      'asset_id': assetId,
    });
    if (result == null) return null;
    return ProxyInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Get the list of available built-in templates.
  ///
  /// Returns a list of [TemplateInfo] objects describing each template,
  /// including its category, duration, and placeholder count.
  Future<List<TemplateInfo>> getTemplates() async {
    final result = await _call<dynamic>('get_templates', {});
    return (result as List)
        .map((e) => TemplateInfo.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  /// Get details for a specific template by its ID.
  ///
  /// Returns `null` if no template with the given ID exists.
  Future<TemplateInfo?> getTemplateDetails({required String templateId}) async {
    final result = await _call<dynamic>('get_template_details', {
      'template_id': templateId,
    });
    if (result == null) return null;
    return TemplateInfo.fromJson(result as Map<String, dynamic>);
  }

  /// Create a new project from a template by filling placeholder slots.
  ///
  /// [templateId] identifies which built-in template to use.
  /// [assignments] is a map of slot ID → media file path.
  /// Slots without assignments are filled with placeholder (black) clips.
  ///
  /// Returns a [ProjectInfo] DTO for the newly created project.
  Future<ProjectInfo> instantiateTemplate({
    required String templateId,
    required Map<String, String> assignments,
  }) async {
    final result = await _call<dynamic>('instantiate_template', {
      'template_id': templateId,
      'assignments': assignments,
    });
    return ProjectInfo.fromJson(result as Map<String, dynamic>);
  }

  // ─── Transcription Operations (Phase 10) ──────────────────────────

  /// Transcribe audio from a media asset.
  ///
  /// Uses the built-in transcription engine to convert speech in the
  /// audio to timestamped text segments. [language] should be a language
  /// code (e.g., "en", "es") or "auto" for auto-detection.
  ///
  /// Returns a list of [TranscriptionSegmentInfo] DTOs.
  Future<List<TranscriptionSegmentInfo>> transcribeAudio({
    required String assetId,
    required String language,
  }) async {
    final result = await _call<dynamic>('transcribe_audio', {
      'asset_id': assetId,
      'language': language,
    });
    return (result as List)
        .map((e) =>
            TranscriptionSegmentInfo.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  /// Create text clips on a text track from a transcription result.
  ///
  /// Transcribes the audio from the given asset and creates text clips
  /// on the specified track, one for each transcription segment.
  /// Returns the IDs of the newly created text clips.
  Future<List<String>> addSubtitlesFromTranscription({
    required String assetId,
    required String trackId,
  }) async {
    final result = await _call<dynamic>(
        'add_subtitles_from_transcription', {
      'asset_id': assetId,
      'track_id': trackId,
    });
    return List<String>.from(result as List);
  }
}

// ═══════════════════════════════════════════════════════════════════════
// Phase 16-17: Performance Profiling Bridge Types
// ═══════════════════════════════════════════════════════════════════════

/// Bridge-compatible performance snapshot from the engine
class PerformanceSnapshotInfo {
  final double averageFps;
  final double targetFps;
  final double dropRate;
  final double avgFrameMs;
  final double p95FrameMs;
  final double avgDecodeMs;
  final double avgRenderMs;
  final double cacheHitRate;
  final int cachedFrameCount;
  final double bufferPoolHitRate;
  final int pooledBufferCount;
  final double memoryRssMb;
  final double memoryPeakMb;
  final double memoryAvailableMb;
  final String memoryPressureLevel;
  final bool gpuAvailable;
  final String gpuAdapterName;
  final String gpuBackendName;
  final double averageExportFps;
  final bool isOnBudget;

  const PerformanceSnapshotInfo({
    required this.averageFps,
    required this.targetFps,
    required this.dropRate,
    required this.avgFrameMs,
    required this.p95FrameMs,
    required this.avgDecodeMs,
    required this.avgRenderMs,
    required this.cacheHitRate,
    required this.cachedFrameCount,
    required this.bufferPoolHitRate,
    required this.pooledBufferCount,
    required this.memoryRssMb,
    required this.memoryPeakMb,
    required this.memoryAvailableMb,
    required this.memoryPressureLevel,
    required this.gpuAvailable,
    required this.gpuAdapterName,
    required this.gpuBackendName,
    required this.averageExportFps,
    required this.isOnBudget,
  });

  factory PerformanceSnapshotInfo.fromJson(Map<String, dynamic> json) =>
      PerformanceSnapshotInfo(
        averageFps: (json['average_fps'] as num).toDouble(),
        targetFps: (json['target_fps'] as num).toDouble(),
        dropRate: (json['drop_rate'] as num).toDouble(),
        avgFrameMs: (json['avg_frame_ms'] as num).toDouble(),
        p95FrameMs: (json['p95_frame_ms'] as num).toDouble(),
        avgDecodeMs: (json['avg_decode_ms'] as num).toDouble(),
        avgRenderMs: (json['avg_render_ms'] as num).toDouble(),
        cacheHitRate: (json['cache_hit_rate'] as num).toDouble(),
        cachedFrameCount: json['cached_frame_count'] as int? ?? 0,
        bufferPoolHitRate: (json['buffer_pool_hit_rate'] as num).toDouble(),
        pooledBufferCount: json['pooled_buffer_count'] as int? ?? 0,
        memoryRssMb: (json['memory_rss_mb'] as num).toDouble(),
        memoryPeakMb: (json['memory_peak_mb'] as num).toDouble(),
        memoryAvailableMb: (json['memory_available_mb'] as num).toDouble(),
        memoryPressureLevel: json['memory_pressure_level'] as String? ?? 'normal',
        gpuAvailable: json['gpu_available'] as bool? ?? false,
        gpuAdapterName: json['gpu_adapter_name'] as String? ?? '',
        gpuBackendName: json['gpu_backend_name'] as String? ?? '',
        averageExportFps: (json['average_export_fps'] as num).toDouble(),
        isOnBudget: json['is_on_budget'] as bool? ?? true,
      );

  Map<String, dynamic> toJson() => {
        'average_fps': averageFps,
        'target_fps': targetFps,
        'drop_rate': dropRate,
        'avg_frame_ms': avgFrameMs,
        'p95_frame_ms': p95FrameMs,
        'avg_decode_ms': avgDecodeMs,
        'avg_render_ms': avgRenderMs,
        'cache_hit_rate': cacheHitRate,
        'cached_frame_count': cachedFrameCount,
        'buffer_pool_hit_rate': bufferPoolHitRate,
        'pooled_buffer_count': pooledBufferCount,
        'memory_rss_mb': memoryRssMb,
        'memory_peak_mb': memoryPeakMb,
        'memory_available_mb': memoryAvailableMb,
        'memory_pressure_level': memoryPressureLevel,
        'gpu_available': gpuAvailable,
        'gpu_adapter_name': gpuAdapterName,
        'gpu_backend_name': gpuBackendName,
        'average_export_fps': averageExportFps,
        'is_on_budget': isOnBudget,
      };
}

/// Bridge-compatible profiler span statistics
class SpanStatsInfo {
  final String name;
  final int callCount;
  final double totalMs;
  final double meanMs;
  final double minMs;
  final double maxMs;
  final double p99Ms;
  final double stdDevMs;

  const SpanStatsInfo({
    required this.name,
    required this.callCount,
    required this.totalMs,
    required this.meanMs,
    required this.minMs,
    required this.maxMs,
    required this.p99Ms,
    required this.stdDevMs,
  });

  factory SpanStatsInfo.fromJson(Map<String, dynamic> json) => SpanStatsInfo(
        name: json['name'] as String,
        callCount: json['call_count'] as int,
        totalMs: (json['total_ms'] as num).toDouble(),
        meanMs: (json['mean_ms'] as num).toDouble(),
        minMs: (json['min_ms'] as num).toDouble(),
        maxMs: (json['max_ms'] as num).toDouble(),
        p99Ms: (json['p99_ms'] as num).toDouble(),
        stdDevMs: (json['std_dev_ms'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'name': name,
        'call_count': callCount,
        'total_ms': totalMs,
        'mean_ms': meanMs,
        'min_ms': minMs,
        'max_ms': maxMs,
        'p99_ms': p99Ms,
        'std_dev_ms': stdDevMs,
      };

  @override
  String toString() =>
      '$name: calls=$callCount, mean=${meanMs.toStringAsFixed(2)}ms, '
      'p99=${p99Ms.toStringAsFixed(2)}ms';
}

// ═══════════════════════════════════════════════════════════════════════
// Phase 17: Free Functions (Bridge Codegen)
// ═══════════════════════════════════════════════════════════════════════

/// Enable or disable profiling globally.
Future<void> setProfilingEnabled({required bool enabled}) async {
  await RustLib.instance.api._call<void>('set_profiling_enabled', {
    'enabled': enabled,
  });
}

/// Check if profiling is currently enabled.
Future<bool> isProfilingEnabled() async {
  final result = await RustLib.instance.api._call<dynamic>('is_profiling_enabled', {});
  return result as bool;
}

/// Get a performance snapshot from the engine.
Future<PerformanceSnapshotInfo> getPerformanceSnapshot() async {
  final result = await RustLib.instance.api._call<dynamic>('get_performance_snapshot', {});
  return PerformanceSnapshotInfo.fromJson(result as Map<String, dynamic>);
}

/// Get the profiler report as a list of span statistics.
Future<List<SpanStatsInfo>> getProfilerReport() async {
  final result = await RustLib.instance.api._call<dynamic>('get_profiler_report', {});
  return (result as List)
      .map((e) => SpanStatsInfo.fromJson(e as Map<String, dynamic>))
      .toList();
}

/// Reset all profiler statistics.
Future<void> resetProfiler() async {
  await RustLib.instance.api._call<void>('reset_profiler', {});
}

/// Get the engine version string.
Future<String> getEngineVersion() async {
  final result = await RustLib.instance.api._call<dynamic>('get_engine_version', {});
  return result as String;
}

/// Get the memory pressure level ("normal", "warning", "critical").
Future<String> getMemoryPressureLevel() async {
  final result = await RustLib.instance.api._call<dynamic>('get_memory_pressure_level', {});
  return result as String;
}

/// Get current memory usage in bytes.
Future<int> getMemoryUsageBytes() async {
  final result = await RustLib.instance.api._call<dynamic>('get_memory_usage_bytes', {});
  return result as int;
}

/// Check if the engine should release caches due to memory pressure.
Future<bool> shouldReleaseCaches() async {
  final result = await RustLib.instance.api._call<dynamic>('should_release_caches', {});
  return result as bool;
}

/// Check if the engine should reduce quality due to memory pressure.
Future<bool> shouldReduceQuality() async {
  final result = await RustLib.instance.api._call<dynamic>('should_reduce_quality', {});
  return result as bool;
}

// ═══════════════════════════════════════════════════════════════════════
// Phase F: Pro Tools FFI wrappers
//
// Wrappers for the new pro tools dispatch arms in
// engine/src/api/ffi_dispatch.rs (lines 883–1117). These methods are
// called by the new Flutter UI widgets in lib/features/editor/widgets/.
// Each wrapper documents the engine method it calls and the types it
// returns. See docs/PRO_TOOLS.md and persona/skills/*/SKILL.md.
// ═══════════════════════════════════════════════════════════════════════

// ─── LUT management (engine/src/effects/lut.rs) ────────────────────────

/// Parse a `.cube` LUT file from its string content. Returns the parsed
/// LUT as a JSON-compatible map (`{kind: "Lut1D" | "Lut3D", ...}`).
///
/// Engine method: `lut_load_cube_content`.
/// See persona/skills/lut-management/SKILL.md.
Future<Map<String, dynamic>> lutLoadCubeContent({required String content}) async {
  final result = await RustLib.instance.api
      ._call<dynamic>('lut_load_cube_content', {'content': content});
  return (result as Map).cast<String, dynamic>();
}

/// Load a `.cube` LUT file from disk. Returns the parsed LUT.
///
/// Engine method: `lut_load_cube`.
Future<Map<String, dynamic>> lutLoadCube({required String path}) async {
  final result = await RustLib.instance.api
      ._call<dynamic>('lut_load_cube', {'path': path});
  return (result as Map).cast<String, dynamic>();
}

// ─── Color scopes (engine/src/analysis/scopes.rs) ──────────────────────

/// Compute waveform, vectorscope, RGB parade, and histogram from a frame.
///
/// `frameBase64` is the RGBA8 pixel data, base64-encoded.
/// Returns a `Scopes` JSON map.
///
/// Engine method: `compute_scopes`.
/// See persona/skills/color-scopes/SKILL.md.
Future<Map<String, dynamic>> computeScopes({
  required String frameBase64,
  required int width,
  required int height,
}) async {
  final result = await RustLib.instance.api._call<dynamic>('compute_scopes', {
    'frame': frameBase64,
    'width': width,
    'height': height,
  });
  return (result as Map).cast<String, dynamic>();
}

/// Count out-of-range pixels in a frame for broadcast QC.
///
/// Engine method: `count_out_of_range_pixels`.
/// See persona/skills/broadcast-legal/SKILL.md.
Future<Map<String, dynamic>> countOutOfRangePixels({
  required String frameBase64,
}) async {
  final result = await RustLib.instance.api
      ._call<dynamic>('count_out_of_range_pixels', {'frame': frameBase64});
  return (result as Map).cast<String, dynamic>();
}

// ─── Color legalizer (engine/src/effects/legalizer.rs) ─────────────────

/// Apply Rec.709 broadcast-legal clamping (with optional soft-clip) to a
/// frame. Returns the legalized frame as base64.
///
/// Engine method: `legalize_frame`.
/// See persona/skills/broadcast-legal/SKILL.md.
Future<String> legalizeFrame({
  required String frameBase64,
  bool softClip = true,
  double knee = 0.9,
}) async {
  final result = await RustLib.instance.api._call<dynamic>('legalize_frame', {
    'frame': frameBase64,
    'soft_clip': softClip,
    'knee': knee,
  });
  return result as String;
}

// ─── Video stabilization (engine/src/effects/stabilization.rs) ─────────

/// Estimate per-frame motion between two consecutive frames.
///
/// Returns `{dx: f32, dy: f32}` in pixels.
///
/// Engine method: `estimate_motion`.
/// See persona/skills/video-stabilization/SKILL.md.
Future<Map<String, dynamic>> estimateMotion({
  required String prevFrameBase64,
  required String currFrameBase64,
  required int width,
  required int height,
  int blockSize = 32,
  int searchRange = 16,
}) async {
  final result = await RustLib.instance.api._call<dynamic>('estimate_motion', {
    'prev': prevFrameBase64,
    'curr': currFrameBase64,
    'width': width,
    'height': height,
    'block_size': blockSize,
    'search_range': searchRange,
  });
  return (result as Map).cast<String, dynamic>();
}

// ─── Color match (engine/src/effects/color_match.rs) ───────────────────

/// Compute a per-channel LUT (256 entries per channel) that maps the
/// source frame's histogram to match the reference frame.
///
/// Engine method: `compute_color_match_lut`.
/// See persona/skills/color-match-shots/SKILL.md.
Future<Map<String, dynamic>> computeColorMatchLut({
  required String sourceFrameBase64,
  required String referenceFrameBase64,
  required int width,
  required int height,
}) async {
  final result = await RustLib.instance.api._call<dynamic>(
    'compute_color_match_lut',
    {
      'source': sourceFrameBase64,
      'reference': referenceFrameBase64,
      'width': width,
      'height': height,
    },
  );
  return (result as Map).cast<String, dynamic>();
}

// ─── Sky replacement (engine/src/effects/sky_replace.rs) ───────────────

/// Replace the sky in a frame using a luminance key. Returns the
/// composited frame as base64.
///
/// Engine method: `replace_sky`.
/// See persona/skills/sky-replacement/SKILL.md.
Future<String> replaceSky({
  required String frameBase64,
  required String newSkyBase64,
  required int width,
  required int height,
  int lumaThreshold = 180,
  double topPortion = 0.6,
  int feather = 4,
  double intensity = 1.0,
}) async {
  final result = await RustLib.instance.api._call<dynamic>('replace_sky', {
    'frame': frameBase64,
    'new_sky': newSkyBase64,
    'width': width,
    'height': height,
    'luma_threshold': lumaThreshold,
    'top_portion': topPortion,
    'feather': feather,
    'intensity': intensity,
  });
  return result as String;
}

// ─── Beat detection (engine/src/analysis/beat_detect.rs) ───────────────

/// Detect beats in audio samples (f32 PCM, base64-encoded as little-endian bytes).
///
/// Returns `{beats: [{time_ms, strength}], estimated_bpm: f32 | null, duration_ms: u64}`.
///
/// Engine method: `detect_beats`.
/// See persona/skills/beat-sync-cut/SKILL.md.
Future<Map<String, dynamic>> detectBeats({
  required String samplesBase64,
  int sampleRate = 44100,
  int windowSize = 1024,
  int hopSize = 512,
  double minStrength = 0.3,
  int minIntervalMs = 200,
}) async {
  final result = await RustLib.instance.api._call<dynamic>('detect_beats', {
    'samples': samplesBase64,
    'sample_rate': sampleRate,
    'window_size': windowSize,
    'hop_size': hopSize,
    'min_strength': minStrength,
    'min_interval_ms': minIntervalMs,
  });
  return (result as Map).cast<String, dynamic>();
}

// ─── Batch export queue (engine/src/export_engine/batch.rs) ────────────

/// Enqueue a new batch export job. Returns the assigned job ID.
///
/// Engine method: `batch_enqueue`.
/// See persona/skills/batch-export/SKILL.md.
Future<String> batchEnqueue({
  required String name,
  required String projectPath,
  required String outputPath,
  required String preset,
}) async {
  final result = await RustLib.instance.api._call<dynamic>('batch_enqueue', {
    'name': name,
    'project_path': projectPath,
    'output_path': outputPath,
    'preset': preset,
  });
  return result as String;
}

/// Get all jobs in the batch queue.
///
/// Engine method: `batch_jobs`.
Future<List<Map<String, dynamic>>> batchJobs() async {
  final result = await RustLib.instance.api._call<dynamic>('batch_jobs', {});
  return (result as List)
      .map((e) => (e as Map).cast<String, dynamic>())
      .toList();
}

/// Cancel a queued or running batch export job.
///
/// Engine method: `batch_cancel`.
Future<void> batchCancel({required String jobId}) async {
  await RustLib.instance.api._call<dynamic>('batch_cancel', {
    'job_id': jobId,
  });
}

/// Clear completed/failed/cancelled jobs from the queue.
///
/// Engine method: `batch_clear_finished`.
Future<void> batchClearFinished() async {
  await RustLib.instance.api._call<dynamic>('batch_clear_finished', {});
}

// ─── Format interop (engine/src/project/interop.rs) ────────────────────

/// Export a timeline to EDL, FCPXML, or OpenTimelineIO format.
///
/// `format` must be one of: `"edl"`, `"fcpxml"`, `"otio"`.
/// Returns the exported file content as a string.
///
/// Engine method: `export_interop`.
/// See persona/skills/format-interop/SKILL.md.
Future<String> exportInterop({
  required Map<String, dynamic> timeline,
  required String format,
}) async {
  final result = await RustLib.instance.api._call<dynamic>('export_interop', {
    'timeline': timeline,
    'format': format,
  });
  return result as String;
}

// ─── Advanced trim (engine/src/timeline/advanced_trim.rs) ──────────────

/// Validate an advanced trim operation (ripple/roll/slip/slide).
/// Returns `true` if legal, throws with an error message otherwise.
///
/// Engine method: `validate_advanced_trim`.
/// See persona/skills/ripple-roll-trim/SKILL.md.
Future<bool> validateAdvancedTrim({
  required Map<String, dynamic> params,
  int clipDurationMs = 0,
  int clipInMs = 0,
  int clipOutMs = 0,
  int clipStartMs = 0,
  int? adjDurationMs,
  int? adjInMs,
  int? adjOutMs,
  int? adjStartMs,
}) async {
  final args = <String, dynamic>{
    'params': params,
    'clip_duration_ms': clipDurationMs,
    'clip_in_ms': clipInMs,
    'clip_out_ms': clipOutMs,
    'clip_start_ms': clipStartMs,
  };
  if (adjDurationMs != null) args['adj_duration_ms'] = adjDurationMs;
  if (adjInMs != null) args['adj_in_ms'] = adjInMs;
  if (adjOutMs != null) args['adj_out_ms'] = adjOutMs;
  if (adjStartMs != null) args['adj_start_ms'] = adjStartMs;
  final result = await RustLib.instance.api._call<dynamic>('validate_advanced_trim', args);
  return result as bool;
}

// ─── Phase F.3: Engine-wired pro tools FFI wrappers ────────────────────
//
// These wrappers finish the F.2 stubbed integrations. Each calls the
// matching engine dispatch arm added in Phase F.3:
//   - applyLutToFrame  → apply_lut_to_frame  (effects/lut.rs)
//   - applyEqToSamples → apply_eq_to_samples (audio/effects.rs)
//   - markersAdd       → markers_add         (effects/markers.rs)
//   - markersGet       → markers_get         (effects/markers.rs)
//   - markersRemove    → markers_remove      (effects/markers.rs)
//   - analyzeLoudness  → analyze_loudness    (analysis/loudness.rs)

/// Apply a previously-loaded LUT to a frame.
///
/// `lutJson` is the parsed LUT returned by [lutLoadCubeContent].
/// `frameBase64` is the RGBA8 pixel data, base64-encoded.
/// `intensity` is 0.0 (no LUT) to 1.0 (full LUT).
///
/// Returns the LUT-applied frame as base64.
///
/// Engine method: `apply_lut_to_frame`.
/// See persona/skills/lut-management/SKILL.md.
Future<String> applyLutToFrame({
  required Map<String, dynamic> lutJson,
  required String frameBase64,
  required int width,
  required int height,
  double intensity = 1.0,
}) async {
  final result = await RustLib.instance.api._call<dynamic>('apply_lut_to_frame', {
    'lut_json': lutJson,
    'frame': frameBase64,
    'width': width,
    'height': height,
    'intensity': intensity,
  });
  return result as String;
}

/// Apply an EQ chain (HPF + 8 peaking bands + LPF) to f32 PCM samples.
///
/// `samplesBase64` is the f32 PCM, base64-encoded as little-endian bytes.
/// Returns the EQ-processed samples as base64 (same encoding).
///
/// Engine method: `apply_eq_to_samples`.
/// See persona/skills/dialogue-cleanup/SKILL.md.
Future<String> applyEqToSamples({
  required Map<String, dynamic> settings,
  required String samplesBase64,
  int sampleRate = 44100,
}) async {
  final result = await RustLib.instance.api._call<dynamic>('apply_eq_to_samples', {
    'settings': settings,
    'samples': samplesBase64,
    'sample_rate': sampleRate,
  });
  return result as String;
}

/// Add a marker to the timeline. Persisted in the engine's marker manager.
///
/// `color` must be one of: red, orange, yellow, green, blue, purple, pink, gray.
/// `markerType` must be one of: standard, chapter, comment, todo, error, musicbeat, custom.
///
/// Returns the created marker (with assigned ID) as JSON.
///
/// Engine method: `markers_add`.
/// See persona/skills/broadcast-legal/SKILL.md (markers tab).
Future<Map<String, dynamic>> markersAdd({
  required String name,
  required double positionMs,
  String color = 'blue',
  String markerType = 'standard',
  String comment = '',
}) async {
  final result = await RustLib.instance.api._call<dynamic>('markers_add', {
    'name': name,
    'position_ms': positionMs,
    'color': color,
    'marker_type': markerType,
    'comment': comment,
  });
  return (result as Map).cast<String, dynamic>();
}

/// Get all markers, sorted by position.
///
/// Engine method: `markers_get`.
Future<List<Map<String, dynamic>>> markersGet() async {
  final result = await RustLib.instance.api._call<dynamic>('markers_get', {});
  return (result as List)
      .map((e) => (e as Map).cast<String, dynamic>())
      .toList();
}

/// Remove a marker by ID. Returns the removed marker as JSON, or throws
/// if the marker was not found.
///
/// Engine method: `markers_remove`.
Future<Map<String, dynamic>> markersRemove({required String id}) async {
  final result = await RustLib.instance.api._call<dynamic>('markers_remove', {
    'id': id,
  });
  return (result as Map).cast<String, dynamic>();
}

/// Analyze loudness of arbitrary f32 PCM samples.
///
/// `samplesBase64` is the f32 PCM, base64-encoded as little-endian bytes.
/// Returns `{integrated_lufs, short_term_lufs, momentary_lufs, rms_db, peak_db, true_peak_dbtp}`.
///
/// Engine method: `analyze_loudness`.
/// See persona/skills/loudness-target/SKILL.md.
Future<Map<String, dynamic>> analyzeLoudness({
  required String samplesBase64,
  int sampleRate = 44100,
  int channels = 2,
}) async {
  final result = await RustLib.instance.api._call<dynamic>('analyze_loudness', {
    'samples': samplesBase64,
    'sample_rate': sampleRate,
    'channels': channels,
  });
  return (result as Map).cast<String, dynamic>();
}
